In [49]:
import sqlite3  # sqlite3 모듈 임포트
import pandas as pd  # pandas 모듈 임포트

# 엑셀 파일 경로
excel_file = '/Users/admin/Documents/GitHub/softeer_wiki/missions/w1/sqltut.xlsx'

# 데이터베이스 파일 경로
database_file = 'df4.db'

# 엑셀 파일을 판다스 데이터프레임으로 읽기 (모든 시트)
xls = pd.ExcelFile(excel_file)

# SQLite 데이터베이스 연결 생성
conn = sqlite3.connect(database_file)

# 각 시트를 반복하면서 데이터베이스에 테이블로 저장
for sheet_name in xls.sheet_names:
    # 각 시트를 데이터프레임으로 변환
    df = pd.read_excel(xls, sheet_name=sheet_name)
    # 각 컬럼별로 map 함수를 사용하여 변환
    for col in df.columns:
        if df[col].dtype == 'object':  # 문자열 데이터 타입 확인
            df[col] = df[col].map(lambda x: x.replace('\xa0', '').replace('\xa9', '') if isinstance(x, str) else x)
    # 숫자 타입 컬럼을 숫자로 변환
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='ignore')
            
    # 데이터프레임을 SQLite 데이터베이스 테이블로 저장
    df.to_sql(sheet_name, conn, if_exists='replace', index=False)

/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')
/var/folders/gv/h6tkbjcs4j325ypvzj8m08qc0000gn/T/ipykernel_25137/2275542125.py:26: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors='ignore')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SupplierID    29 non-null     int64
 1   SupplierName  29 non-null     object
 2   ContactName   29 non-null     object
 3   Address       29 non-null     object
 4   City          29 non-null     object
 5   PostalCode    29 non-null     object
 6   Country       29 non-null     object
 7   Phone         29 non-null     object
dtypes: int64(1), object(7)
memory usage: 1.9+ KB

# 기본 구문

### SELECT

In [51]:
cursor = conn.cursor()
query='SELECT * FROM Customers;'
cursor.execute(query)
result= cursor.fetchone()
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', None, 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)

In [52]:
cursor = conn.cursor()
query='SELECT CustomerName, City FROM Customers;'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerName', 'City']
('Alfreds Futterkiste', 'Berlin')
('Ana Trujillo Emparedados y helados', 'México D.F.')
('Antonio Moreno Taquería', 'México D.F.')
('Around the Horn', 'London')
('Berglunds snabbköp', 'Luleå')
('Blauer See Delikatessen', 'Mannheim')
('Blondel père et fils', 'Strasbourg')
('Bólido Comidas preparadas', 'Madrid')
("Bon app'", 'Marseille')
('Bottom-Dollar Marketse', 'Tsawassen')
("B's Beverages", 'London')
('Cactus Comidas para llevar', 'Buenos Aires')
('Centro comercial Moctezuma', 'México D.F.')
('Chop-suey Chinese', 'Bern')
('Comércio Mineiro', 'São Paulo')
('Consolidated Holdings', 'London')
('Drachenblut Delikatessend', 'Aachen')
('Du monde entier', 'Nantes')
('Eastern Connection', 'London')
('Ernst Handel', 'Graz')
('Familia Arquibaldo', 'São Paulo')
('FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Folies gourmandes', 'Lille')
('Folk och fä HB', 'Bräcke')
('Frankenversand', 'München')
('France restauration', 'Nantes')
('Franchi S.p.A.', 'Torino')
('Furia Bacalhau e Frutos do Mar', 'Lisboa')
('Galería del gastrónomo', 'Barcelona')
('Godos Cocina Típica', 'Sevilla')
('Gourmet Lanchonetes', 'Campinas')
('Great Lakes Food Market', 'Eugene')
('GROSELLA-Restaurante', 'Caracas')
('Hanari Carnes', 'Rio de Janeiro')
('HILARIÓN-Abastos', 'San Cristóbal')
('Hungry Coyote Import Store', 'Elgin')
('Hungry Owl All-Night Grocers', 'Cork')
('Island Trading', 'Cowes')
('Königlich Essen', 'Brandenburg')
("La corne d'abondance", 'Versailles')
("La maison d'Asie", 'Toulouse')
('Laughing Bacchus Wine Cellars', 'Vancouver')
('Lazy K Kountry Store', 'Walla Walla')
('Lehmanns Marktstand', 'Frankfurt a.M. ')
("Let's Stop N Shop", 'San Francisco')
('LILA-Supermercado', 'Barquisimeto')
('LINO-Delicateses', 'I. de Margarita')
('Lonesome Pine Restaurant', 'Portland')
('Magazzini Alimentari Riuniti', 'Bergamo')
('Maison Dewey', 'Bruxelles')
('Mère Paillarde', 'Montréal')
('Morgenstern Gesundkost', 'Leipzig')
('North/South', 'London')
('Océano Atlántico Ltda.', 'Buenos Aires')
('Old World Delicatessen', 'Anchorage')
('Ottilies Käseladen', 'Köln')
('Paris spécialités', 'Paris')
('Pericles Comidas clásicas', 'México D.F.')
('Piccolo und mehr', 'Salzburg')
('Princesa Isabel Vinhoss', 'Lisboa')
('Que Delícia', 'Rio de Janeiro')
('Queen Cozinha', 'São Paulo')
('QUICK-Stop', 'Cunewalde')
('Rancho grande', 'Buenos Aires')
('Rattlesnake Canyon Grocery', 'Albuquerque')
('Reggiani Caseifici', 'Reggio Emilia')
('Ricardo Adocicados', 'Rio de Janeiro')
('Richter Supermarkt', 'Genève')
('Romero y tomillo', 'Madrid')
('Santé Gourmet', 'Stavern')
('Save-a-lot Markets', 'Boise')
('Seven Seas Imports', 'London')
('Simons bistro', 'København')
('Spécialités du monde', 'Paris')
('Split Rail Beer & Ale', 'Lander')
('Suprêmes délices', 'Charleroi')
('The Big Cheese', 'Portland')
('The Cracker Box', 'Butte')
('Toms Spezialitäten', 'Münster')
('Tortuga Restaurante', 'México D.F.')
('Tradição Hipermercados', 'São Paulo')
("Trail's Head Gourmet Provisioners", 'Kirkland')
('Vaffeljernet', 'Århus')
('Victuailles en stock', 'Lyon')
('Vins et alcools Chevalier', 'Reims')
('Die Wandernde Kuh', 'Stuttgart')
('Wartian Herkku', 'Oulu')
('Wellington Importadora', 'Resende')
('White Clover Markets', 'Seattle')
('Wilman Kala', 'Helsinki')
('Wolski', 'Walla')

### DISTINCT 고유값

In [53]:
cursor = conn.cursor()
query='SELECT DISTINCT Country FROM Customers;'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['Country']
('Germany',)
('Mexico',)
('UK',)
('Sweden',)
('France',)
('Spain',)
('Canada',)
('Argentina',)
('Switzerland',)
('Brazil',)
('Austria',)
('Italy',)
('Portugal',)
('USA',)
('Venezuela',)
('Ireland',)
('Belgium',)
('Norway',)
('Denmark',)
('Finland',)
(None,)

### Where

In [54]:
cursor = conn.cursor()
query=''' 
SELECT * FROM Customers 
WHERE Country='Mexico ';
'''
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']

### ORDER BY

In [55]:
cursor = conn.cursor()
query='SELECT * FROM Products ORDER BY Price;'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['ProductID', 'ProductName', 'SupplierID', 'CategoryID', 'Unit', 'Price']
(33, 'Geitost', 15, 4, '500 g', 2.5)
(24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5)
(13, 'Konbu', 6, 8, '2 kg box', 6.0)
(52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7.0)
(54, 'Tourtière', 25, 6, '16 pies', 7.45)
(75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75)
(23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9.0)
(19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2)
(45, 'Røgede sild', 21, 8, '1k pkg.', 9.5)
(47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5)
(41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 9.65)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10.0)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10.0)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10.0)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12.0)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13.0)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14.0)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14.0)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14.0)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14.0)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15.0)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15.0)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17.0)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18.0)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18.0)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18.0)
(76, 'Lakkalikööri', 23, 1, '500 ml ', 18.0)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19.0)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19.0)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20.0)
(11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21.0)
(22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21.0)
(65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05)
(5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21.35)
(71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5)
(4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22.0)
(14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23.25)
(55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24.0)
(6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25.0)
(30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89)
(37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26.0)
(61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 28.5)
(7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30.0)
(10, 'Ikura', 4, 8, '12 - 200 ml jars', 31.0)
(26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23)
(32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32.0)
(53, 'Perth Pasties', 24, 6, '48 pieces', 32.8)
(64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25)
(60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34.0)
(72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8)
(69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36.0)
(12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38.0)
(56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38.0)
(17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39.0)
(8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40.0)
(27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9)
(63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43.9)
(28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6)
(43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46.0)
(62, 'Tarte au sucre', 29, 3, '48 pies', 49.3)
(51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53.0)
(59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55.0)
(18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5)
(20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81.0)
(9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97.0)
(29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79)
(38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5)

### AND

In [56]:
cursor = conn.cursor()

query="SELECT * FROM Customers WHERE Country = 'Spain' AND CustomerName LIKE 'G%';"
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')

### OR

In [57]:
cursor = conn.cursor()

query="SELECT * FROM Customers WHERE Country = 'Germany' OR Country = 'Spain';"
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')

### NOT

In [91]:
cursor = conn.cursor()

query="SELECT * FROM Customers WHERE NOT CustomerID < 50;"
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)

### INSERT INTO

In [59]:
cursor = conn.cursor()

insert_query = '''
INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country) 
VALUES (?, ?, ?, ?, ?, ?)
'''
data = [
    ('Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway'),
    ('Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway'),
    ('Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')
]

cursor.executemany(insert_query, data)
conn.commit()
query = 'SELECT * FROM Customers;'
cursor.execute(query)
#column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', None, 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)
(None, 'Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway')
(None, 'Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway')
(None, 'Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')

### NULL

In [60]:
cursor = conn.cursor()
query = 'SELECT CustomerName, ContactName, Address FROM Customers WHERE Address IS NOT NULL;'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerName', 'ContactName', 'Address']
('Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57')
('Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222')
('Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312')
('Around the Horn', 'Thomas Hardy', '120 Hanover Sq.')
('Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8')
('Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57')
('Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber')
('Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67')
("Bon app'", 'Laurence Lebihans', '12, rue des Bouchers')
('Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.')
("B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus')
('Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333')
('Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993')
('Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29')
('Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23')
('Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ')
('Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21')
('Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages')
('Eastern Connection', 'Ann Devon', '35 King George')
('Ernst Handel', 'Roland Mendel', 'Kirchgasse 6')
('Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92')
('FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86')
('Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai')
('Folk och fä HB', 'Maria Larsson', 'Åkergatan 24')
('Frankenversand', 'Peter Franken', 'Berliner Platz 43')
('France restauration', 'Carine Schmitt', '54, rue Royale')
('Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34')
('Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32')
('Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23')
('Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33')
('Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442')
('Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.')
('GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes')
('Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67')
('HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35')
('Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.')
('Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road')
('Island Trading', 'Helen Bennett', 'Garden House Crowther Way')
('Königlich Essen', 'Philip Cramer', 'Maubelstr. 90')
("La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe")
("La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine')
('Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.')
('Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace')
('Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7')
("Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5')
('LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo')
('LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar')
('Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.')
('Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22')
('Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532')
('Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent')
('Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22')
('North/South', 'Simon Crowther', 'South House 300 Queensbridge')
('Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A')
('Old World Delicatessen', 'Rene Phillips', '2743 Bering St.')
('Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369')
('Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne')
('Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321')
('Piccolo und mehr', 'Georg Pipps', 'Geislweg 14')
('Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58')
('Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12')
('Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891')
('QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10')
('Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900')
('Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.')
('Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124')
('Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267')
('Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237')
('Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1')
('Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78')
('Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.')
('Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.')
('Simons bistro', 'Jytte Petersen', 'Vinbæltet 34')
('Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston')
('Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555')
('Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255')
('The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2')
('The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.')
('Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48')
('Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123')
('Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414')
("Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.')
('Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45')
('Victuailles en stock', 'Mary Saveley', '2, rue du Commerce')
('Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye")
('Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900')
('Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38')
('Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12')
('White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B')
('Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45')
('Wolski', 'Zbyszek', 'ul. Filtrowa 68')
('Cardinal', 'Tom B. Erichsen', 'Skagen 21')
('Greasy Burger', 'Per Olsen', 'Gateveien 15')
('Tasty Tee', 'Finn Egan', 'Streetroad 19B')

### UPDATE

In [61]:
cursor = conn.cursor()
query = '''
UPDATE Customers
SET ContactName='Juan'
WHERE Country='Mexico';
'''
conn.commit()
query = 'SELECT * FROM Customers;'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', None, 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)
(None, 'Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway')
(None, 'Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway')
(None, 'Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')

### DELETE

In [62]:
cursor = conn.cursor()
query = '''
DELETE FROM Customers 
WHERE CustomerName='Alfreds Futterkiste';
'''
conn.commit()
query = 'SELECT * FROM Customers;'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', None, 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)
(None, 'Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway')
(None, 'Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway')
(None, 'Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')

### LIMIT (TOP)

In [63]:
cursor = conn.cursor()
query = ''' 
SELECT * 
FROM Customers
LIMIT 3;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')

# SQL Aggregate Functions

### MIN

In [64]:
cursor = conn.cursor()
query = ''' 
SELECT MIN(Price)
FROM Products;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['MIN(Price)']
(2.5,)

### MAX

In [65]:
cursor = conn.cursor()
query = ''' 
SELECT MAX(Price)
FROM Products;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['MAX(Price)']
(263.5,)

### count

In [66]:
cursor = conn.cursor()
query = ''' 
SELECT COUNT(*)
FROM Products;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['COUNT(*)']
(77,)

### sum

In [67]:
cursor = conn.cursor()
query = ''' 
SELECT SUM(Quantity)
FROM OrderDetails;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['SUM(Quantity)']
(12743,)

### avg

In [68]:
cursor = conn.cursor()
query = ''' 
SELECT AVG(Price)
FROM Products;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['AVG(Price)']
(28.866363636363637,)

### like

In [69]:
cursor = conn.cursor()
query = ''' 
SELECT * FROM Customers
WHERE CustomerName LIKE 'a%';
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')

In [70]:
cursor = conn.cursor()
query = ''' 
SELECT * FROM Customers
WHERE CustomerName LIKE 'a%';
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')

### IN

In [71]:


cursor = conn.cursor()
query = ''' 
SELECT * FROM Customers
WHERE Country IN ('Germany', 'France', 'UK');
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(None, 'Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')

### between

In [72]:


cursor = conn.cursor()
query = ''' 
SELECT * FROM Products
WHERE Price BETWEEN 10 AND 20;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['ProductID', 'ProductName', 'SupplierID', 'CategoryID', 'Unit', 'Price']
(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18.0)
(2, 'Chang', 1, 1, '24 - 12 oz bottles', 19.0)
(3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10.0)
(15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5)
(16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17.45)
(21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10.0)
(25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14.0)
(31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5)
(34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14.0)
(35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18.0)
(36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19.0)
(39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18.0)
(40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4)
(42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14.0)
(44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45)
(46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12.0)
(48, 'Chocolade', 22, 3, '10 pkgs.', 12.75)
(49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20.0)
(50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25)
(57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5)
(58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13.25)
(66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17.0)
(67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14.0)
(68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5)
(70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15.0)
(73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15.0)
(74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10.0)
(76, 'Lakkalikööri', 23, 1, '500 ml ', 18.0)
(77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13.0)

### as 별칭

In [73]:


cursor = conn.cursor()
query = ''' 
SELECT CustomerName AS ID
FROM Customers;
''' 
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['ID']
('Alfreds Futterkiste',)
('Ana Trujillo Emparedados y helados',)
('Antonio Moreno Taquería',)
('Around the Horn',)
('Berglunds snabbköp',)
('Blauer See Delikatessen',)
('Blondel père et fils',)
('Bólido Comidas preparadas',)
("Bon app'",)
('Bottom-Dollar Marketse',)
("B's Beverages",)
('Cactus Comidas para llevar',)
('Centro comercial Moctezuma',)
('Chop-suey Chinese',)
('Comércio Mineiro',)
('Consolidated Holdings',)
('Drachenblut Delikatessend',)
('Du monde entier',)
('Eastern Connection',)
('Ernst Handel',)
('Familia Arquibaldo',)
('FISSA Fabrica Inter. Salchichas S.A.',)
('Folies gourmandes',)
('Folk och fä HB',)
('Frankenversand',)
('France restauration',)
('Franchi S.p.A.',)
('Furia Bacalhau e Frutos do Mar',)
('Galería del gastrónomo',)
('Godos Cocina Típica',)
('Gourmet Lanchonetes',)
('Great Lakes Food Market',)
('GROSELLA-Restaurante',)
('Hanari Carnes',)
('HILARIÓN-Abastos',)
('Hungry Coyote Import Store',)
('Hungry Owl All-Night Grocers',)
('Island Trading',)
('Königlich Essen',)
("La corne d'abondance",)
("La maison d'Asie",)
('Laughing Bacchus Wine Cellars',)
('Lazy K Kountry Store',)
('Lehmanns Marktstand',)
("Let's Stop N Shop",)
('LILA-Supermercado',)
('LINO-Delicateses',)
('Lonesome Pine Restaurant',)
('Magazzini Alimentari Riuniti',)
('Maison Dewey',)
('Mère Paillarde',)
('Morgenstern Gesundkost',)
('North/South',)
('Océano Atlántico Ltda.',)
('Old World Delicatessen',)
('Ottilies Käseladen',)
('Paris spécialités',)
('Pericles Comidas clásicas',)
('Piccolo und mehr',)
('Princesa Isabel Vinhoss',)
('Que Delícia',)
('Queen Cozinha',)
('QUICK-Stop',)
('Rancho grande',)
('Rattlesnake Canyon Grocery',)
('Reggiani Caseifici',)
('Ricardo Adocicados',)
('Richter Supermarkt',)
('Romero y tomillo',)
('Santé Gourmet',)
('Save-a-lot Markets',)
('Seven Seas Imports',)
('Simons bistro',)
('Spécialités du monde',)
('Split Rail Beer & Ale',)
('Suprêmes délices',)
('The Big Cheese',)
('The Cracker Box',)
('Toms Spezialitäten',)
('Tortuga Restaurante',)
('Tradição Hipermercados',)
("Trail's Head Gourmet Provisioners",)
('Vaffeljernet',)
('Victuailles en stock',)
('Vins et alcools Chevalier',)
('Die Wandernde Kuh',)
('Wartian Herkku',)
('Wellington Importadora',)
('White Clover Markets',)
('Wilman Kala',)
('Wolski',)
('Cardinal',)
('Greasy Burger',)
('Tasty Tee',)

# JOIN

### 조인

In [74]:

#['CustomerID', 'EmployeeID', 'OrderDate', 'ShipperID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']

cursor = conn.cursor()#
query = ''' 
SELECT Orders.OrderID, Customers.CustomerName, Orders.OrderDate
FROM Orders
INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;
''' #INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['OrderID', 'CustomerName', 'OrderDate']
(10248, 'Wilman Kala', '7/4/1996')
(10249, 'Tradição Hipermercados', '7/5/1996')
(10250, 'Hanari Carnes', '7/8/1996')
(10251, 'Victuailles en stock', '7/8/1996')
(10252, 'Suprêmes délices', '7/9/1996')
(10253, 'Hanari Carnes', '7/10/1996')
(10254, 'Chop-suey Chinese', '7/11/1996')
(10255, 'Richter Supermarkt', '7/12/1996')
(10256, 'Wellington Importadora', '7/15/1996')
(10257, 'HILARIÓN-Abastos', '7/16/1996')
(10258, 'Ernst Handel', '7/17/1996')
(10259, 'Centro comercial Moctezuma', '7/18/1996')
(10260, 'Old World Delicatessen', '7/19/1996')
(10261, 'Que Delícia', '7/19/1996')
(10262, 'Rattlesnake Canyon Grocery', '7/22/1996')
(10263, 'Ernst Handel', '7/23/1996')
(10264, 'Folk och fä HB', '7/24/1996')
(10265, 'Blondel père et fils', '7/25/1996')
(10266, 'Wartian Herkku', '7/26/1996')
(10267, 'Frankenversand', '7/29/1996')
(10268, 'GROSELLA-Restaurante', '7/30/1996')
(10269, 'White Clover Markets', '7/31/1996')
(10270, 'Wartian Herkku', '8/1/1996')
(10271, 'Split Rail Beer & Ale', '8/1/1996')
(10272, 'Rattlesnake Canyon Grocery', '8/2/1996')
(10273, 'QUICK-Stop', '8/5/1996')
(10274, 'Vins et alcools Chevalier', '8/6/1996')
(10275, 'Magazzini Alimentari Riuniti', '8/7/1996')
(10276, 'Tortuga Restaurante', '8/8/1996')
(10277, 'Morgenstern Gesundkost', '8/9/1996')
(10278, 'Berglunds snabbköp', '8/12/1996')
(10279, 'Lehmanns Marktstand', '8/13/1996')
(10280, 'Berglunds snabbköp', '8/14/1996')
(10281, 'Romero y tomillo', '8/14/1996')
(10282, 'Romero y tomillo', '8/15/1996')
(10283, 'LILA-Supermercado', '8/16/1996')
(10284, 'Lehmanns Marktstand', '8/19/1996')
(10285, 'QUICK-Stop', '8/20/1996')
(10286, 'QUICK-Stop', '8/21/1996')
(10287, 'Ricardo Adocicados', '8/22/1996')
(10288, 'Reggiani Caseifici', '8/23/1996')
(10289, "B's Beverages", '8/26/1996')
(10290, 'Comércio Mineiro', '8/27/1996')
(10291, 'Que Delícia', '8/27/1996')
(10292, 'Tradição Hipermercados', '8/28/1996')
(10293, 'Tortuga Restaurante', '8/29/1996')
(10294, 'Rattlesnake Canyon Grocery', '8/30/1996')
(10295, 'Vins et alcools Chevalier', '9/2/1996')
(10296, 'LILA-Supermercado', '9/3/1996')
(10297, 'Blondel père et fils', '9/4/1996')
(10298, 'Hungry Owl All-Night Grocers', '9/5/1996')
(10299, 'Ricardo Adocicados', '9/6/1996')
(10300, 'Magazzini Alimentari Riuniti', '9/9/1996')
(10301, 'Die Wandernde Kuh', '9/9/1996')
(10302, 'Suprêmes délices', '9/10/1996')
(10303, 'Godos Cocina Típica', '9/11/1996')
(10304, 'Tortuga Restaurante', '9/12/1996')
(10305, 'Old World Delicatessen', '9/13/1996')
(10306, 'Romero y tomillo', '9/16/1996')
(10307, 'Lonesome Pine Restaurant', '9/17/1996')
(10308, 'Ana Trujillo Emparedados y helados', '9/18/1996')
(10309, 'Hungry Owl All-Night Grocers', '9/19/1996')
(10310, 'The Big Cheese', '9/20/1996')
(10311, 'Du monde entier', '9/20/1996')
(10312, 'Die Wandernde Kuh', '9/23/1996')
(10313, 'QUICK-Stop', '9/24/1996')
(10314, 'Rattlesnake Canyon Grocery', '9/25/1996')
(10315, 'Island Trading', '9/26/1996')
(10316, 'Rattlesnake Canyon Grocery', '9/27/1996')
(10317, 'Lonesome Pine Restaurant', '9/30/1996')
(10318, 'Island Trading', '10/1/1996')
(10319, 'Tortuga Restaurante', '10/2/1996')
(10320, 'Wartian Herkku', '10/3/1996')
(10321, 'Island Trading', '10/3/1996')
(10322, 'Pericles Comidas clásicas', '10/4/1996')
(10323, 'Königlich Essen', '10/7/1996')
(10324, 'Save-a-lot Markets', '10/8/1996')
(10325, 'Königlich Essen', '10/9/1996')
(10326, 'Bólido Comidas preparadas', '10/10/1996')
(10327, 'Folk och fä HB', '10/11/1996')
(10328, 'Furia Bacalhau e Frutos do Mar', '10/14/1996')
(10329, 'Split Rail Beer & Ale', '10/15/1996')
(10330, 'LILA-Supermercado', '10/16/1996')
(10331, "Bon app'", '10/16/1996')
(10332, 'Mère Paillarde', '10/17/1996')
(10333, 'Wartian Herkku', '10/18/1996')
(10334, 'Victuailles en stock', '10/21/1996')
(10335, 'Hungry Owl All-Night Grocers', '10/22/1996')
(10336, 'Princesa Isabel Vinhoss', '10/23/1996')
(10337, 'Frankenversand', '10/24/1996')
(10338, 'Old World Delicatessen', '10/25/1996')
(10339, 'Mère Paillarde', '10/28/1996')
(10340, "Bon app'", '10/29/1996')
(10341, 'Simons bistro', '10/29/1996')
(10342, 'Frankenversand', '10/30/1996')
(10343, 'Lehmanns Marktstand', '10/31/1996')
(10344, 'White Clover Markets', '11/1/1996')
(10345, 'QUICK-Stop', '11/4/1996')
(10346, 'Rattlesnake Canyon Grocery', '11/5/1996')
(10347, 'Familia Arquibaldo', '11/6/1996')
(10348, 'Die Wandernde Kuh', '11/7/1996')
(10349, 'Split Rail Beer & Ale', '11/8/1996')
(10350, "La maison d'Asie", '11/11/1996')
(10351, 'Ernst Handel', '11/11/1996')
(10352, 'Furia Bacalhau e Frutos do Mar', '11/12/1996')
(10353, 'Piccolo und mehr', '11/13/1996')
(10354, 'Pericles Comidas clásicas', '11/14/1996')
(10355, 'Around the Horn', '11/15/1996')
(10356, 'Die Wandernde Kuh', '11/18/1996')
(10357, 'LILA-Supermercado', '11/19/1996')
(10358, "La maison d'Asie", '11/20/1996')
(10359, 'Seven Seas Imports', '11/21/1996')
(10360, 'Blondel père et fils', '11/22/1996')
(10361, 'QUICK-Stop', '11/22/1996')
(10362, "Bon app'", '11/25/1996')
(10363, 'Drachenblut Delikatessend', '11/26/1996')
(10364, 'Eastern Connection', '11/26/1996')
(10365, 'Antonio Moreno Taquería', '11/27/1996')
(10366, 'Galería del gastrónomo', '11/28/1996')
(10367, 'Vaffeljernet', '11/28/1996')
(10368, 'Ernst Handel', '11/29/1996')
(10369, 'Split Rail Beer & Ale', '12/2/1996')
(10370, 'Chop-suey Chinese', '12/3/1996')
(10371, "La maison d'Asie", '12/3/1996')
(10372, 'Queen Cozinha', '12/4/1996')
(10373, 'Hungry Owl All-Night Grocers', '12/5/1996')
(10374, 'Wolski', '12/5/1996')
(10375, 'Hungry Coyote Import Store', '12/6/1996')
(10376, 'Mère Paillarde', '12/9/1996')
(10377, 'Seven Seas Imports', '12/9/1996')
(10378, 'Folk och fä HB', '12/10/1996')
(10379, 'Que Delícia', '12/11/1996')
(10380, 'Hungry Owl All-Night Grocers', '12/12/1996')
(10381, 'LILA-Supermercado', '12/12/1996')
(10382, 'Ernst Handel', '12/13/1996')
(10383, 'Around the Horn', '12/16/1996')
(10384, 'Berglunds snabbköp', '12/16/1996')
(10385, 'Split Rail Beer & Ale', '12/17/1996')
(10386, 'Familia Arquibaldo', '12/18/1996')
(10387, 'Santé Gourmet', '12/18/1996')
(10388, 'Seven Seas Imports', '12/19/1996')
(10389, 'Bottom-Dollar Marketse', '12/20/1996')
(10390, 'Ernst Handel', '12/23/1996')
(10391, 'Drachenblut Delikatessend', '12/23/1996')
(10392, 'Piccolo und mehr', '12/24/1996')
(10393, 'Save-a-lot Markets', '12/25/1996')
(10394, 'Hungry Coyote Import Store', '12/25/1996')
(10395, 'HILARIÓN-Abastos', '12/26/1996')
(10396, 'Frankenversand', '12/27/1996')
(10397, 'Princesa Isabel Vinhoss', '12/27/1996')
(10398, 'Save-a-lot Markets', '12/30/1996')
(10399, 'Vaffeljernet', '12/31/1996')
(10400, 'Eastern Connection', '1/1/1997')
(10401, 'Rattlesnake Canyon Grocery', '1/1/1997')
(10402, 'Ernst Handel', '1/2/1997')
(10403, 'Ernst Handel', '1/3/1997')
(10404, 'Magazzini Alimentari Riuniti', '1/3/1997')
(10405, 'LINO-Delicateses', '1/6/1997')
(10406, 'Queen Cozinha', '1/7/1997')
(10407, 'Ottilies Käseladen', '1/7/1997')
(10408, 'Folies gourmandes', '1/8/1997')
(10409, 'Océano Atlántico Ltda.', '1/9/1997')
(10410, 'Bottom-Dollar Marketse', '1/10/1997')
(10411, 'Bottom-Dollar Marketse', '1/10/1997')
(10412, 'Wartian Herkku', '1/13/1997')
(10413, "La maison d'Asie", '1/14/1997')
(10414, 'Familia Arquibaldo', '1/14/1997')
(10415, 'Hungry Coyote Import Store', '1/15/1997')
(10416, 'Wartian Herkku', '1/16/1997')
(10417, 'Simons bistro', '1/16/1997')
(10418, 'QUICK-Stop', '1/17/1997')
(10419, 'Richter Supermarkt', '1/20/1997')
(10420, 'Wellington Importadora', '1/21/1997')
(10421, 'Que Delícia', '1/21/1997')
(10422, 'Franchi S.p.A.', '1/22/1997')
(10423, 'Gourmet Lanchonetes', '1/23/1997')
(10424, 'Mère Paillarde', '1/23/1997')
(10425, "La maison d'Asie", '1/24/1997')
(10426, 'Galería del gastrónomo', '1/27/1997')
(10427, 'Piccolo und mehr', '1/27/1997')
(10428, 'Reggiani Caseifici', '1/28/1997')
(10429, 'Hungry Owl All-Night Grocers', '1/29/1997')
(10430, 'Ernst Handel', '1/30/1997')
(10431, 'Bottom-Dollar Marketse', '1/30/1997')
(10432, 'Split Rail Beer & Ale', '1/31/1997')
(10433, 'Princesa Isabel Vinhoss', '2/3/1997')
(10434, 'Folk och fä HB', '2/3/1997')
(10435, 'Consolidated Holdings', '2/4/1997')
(10436, 'Blondel père et fils', '2/5/1997')
(10437, 'Wartian Herkku', '2/5/1997')
(10438, 'Toms Spezialitäten', '2/6/1997')
(10439, 'Mère Paillarde', '2/7/1997')
(10440, 'Save-a-lot Markets', '2/10/1997')
(10441, 'Old World Delicatessen', '2/10/1997')
(10442, 'Ernst Handel', '2/11/1997')
(10443, 'Reggiani Caseifici', '2/12/1997')

### 내부조인 INNER

In [75]:

cursor = conn.cursor()#
query = ''' 
SELECT ProductID, ProductName, CategoryName
FROM Products
INNER JOIN Categories ON Products.CategoryID = Categories.CategoryID;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['ProductID', 'ProductName', 'CategoryName']
(1, 'Chais', 'Beverages')
(2, 'Chang', 'Beverages')
(3, 'Aniseed Syrup', 'Condiments')
(4, "Chef Anton's Cajun Seasoning", 'Condiments')
(5, "Chef Anton's Gumbo Mix", 'Condiments')
(6, "Grandma's Boysenberry Spread", 'Condiments')
(7, "Uncle Bob's Organic Dried Pears", 'Produce')
(8, 'Northwoods Cranberry Sauce', 'Condiments')
(9, 'Mishi Kobe Niku', 'Meat/Poultry')
(10, 'Ikura', 'Seafood')
(11, 'Queso Cabrales', 'Dairy Products')
(12, 'Queso Manchego La Pastora', 'Dairy Products')
(13, 'Konbu', 'Seafood')
(14, 'Tofu', 'Produce')
(15, 'Genen Shouyu', 'Condiments')
(16, 'Pavlova', 'Confections')
(17, 'Alice Mutton', 'Meat/Poultry')
(18, 'Carnarvon Tigers', 'Seafood')
(19, 'Teatime Chocolate Biscuits', 'Confections')
(20, "Sir Rodney's Marmalade", 'Confections')
(21, "Sir Rodney's Scones", 'Confections')
(22, "Gustaf's Knäckebröd", 'Grains/Cereals')
(23, 'Tunnbröd', 'Grains/Cereals')
(24, 'Guaraná Fantástica', 'Beverages')
(25, 'NuNuCa Nuß-Nougat-Creme', 'Confections')
(26, 'Gumbär Gummibärchen', 'Confections')
(27, 'Schoggi Schokolade', 'Confections')
(28, 'Rössle Sauerkraut', 'Produce')
(29, 'Thüringer Rostbratwurst', 'Meat/Poultry')
(30, 'Nord-Ost Matjeshering', 'Seafood')
(31, 'Gorgonzola Telino', 'Dairy Products')
(32, 'Mascarpone Fabioli', 'Dairy Products')
(33, 'Geitost', 'Dairy Products')
(34, 'Sasquatch Ale', 'Beverages')
(35, 'Steeleye Stout', 'Beverages')
(36, 'Inlagd Sill', 'Seafood')
(37, 'Gravad lax', 'Seafood')
(38, 'Côte de Blaye', 'Beverages')
(39, 'Chartreuse verte', 'Beverages')
(40, 'Boston Crab Meat', 'Seafood')
(41, "Jack's New England Clam Chowder", 'Seafood')
(42, 'Singaporean Hokkien Fried Mee', 'Grains/Cereals')
(43, 'Ipoh Coffee', 'Beverages')
(44, 'Gula Malacca', 'Condiments')
(45, 'Røgede sild', 'Seafood')
(46, 'Spegesild', 'Seafood')
(47, 'Zaanse koeken', 'Confections')
(48, 'Chocolade', 'Confections')
(49, 'Maxilaku', 'Confections')
(50, 'Valkoinen suklaa', 'Confections')
(51, 'Manjimup Dried Apples', 'Produce')
(52, 'Filo Mix', 'Grains/Cereals')
(53, 'Perth Pasties', 'Meat/Poultry')
(54, 'Tourtière', 'Meat/Poultry')
(55, 'Pâté chinois', 'Meat/Poultry')
(56, 'Gnocchi di nonna Alice', 'Grains/Cereals')
(57, 'Ravioli Angelo', 'Grains/Cereals')
(58, 'Escargots de Bourgogne', 'Seafood')
(59, 'Raclette Courdavault', 'Dairy Products')
(60, 'Camembert Pierrot', 'Dairy Products')
(61, "Sirop d'érable", 'Condiments')
(62, 'Tarte au sucre', 'Confections')
(63, 'Vegie-spread', 'Condiments')
(64, 'Wimmers gute Semmelknödel', 'Grains/Cereals')
(65, 'Louisiana Fiery Hot Pepper Sauce', 'Condiments')
(66, 'Louisiana Hot Spiced Okra', 'Condiments')
(67, 'Laughing Lumberjack Lager', 'Beverages')
(68, 'Scottish Longbreads', 'Confections')
(69, 'Gudbrandsdalsost', 'Dairy Products')
(70, 'Outback Lager', 'Beverages')
(71, 'Fløtemysost', 'Dairy Products')
(72, 'Mozzarella di Giovanni', 'Dairy Products')
(73, 'Röd Kaviar', 'Seafood')
(74, 'Longlife Tofu', 'Produce')
(75, 'Rhönbräu Klosterbier', 'Beverages')
(76, 'Lakkalikööri', 'Beverages')
(77, 'Original Frankfurter grüne Soße', 'Condiments')

### LEFT조인

In [76]:

cursor = conn.cursor()
query = ''' 
SELECT Customers.CustomerName, Orders.OrderID
FROM Customers
LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID
ORDER BY Customers.CustomerName;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerName', 'OrderID']
('Alfreds Futterkiste', None)
('Ana Trujillo Emparedados y helados', 10308)
('Antonio Moreno Taquería', 10365)
('Around the Horn', 10355)
('Around the Horn', 10383)
("B's Beverages", 10289)
('Berglunds snabbköp', 10278)
('Berglunds snabbköp', 10280)
('Berglunds snabbköp', 10384)
('Blauer See Delikatessen', None)
('Blondel père et fils', 10265)
('Blondel père et fils', 10297)
('Blondel père et fils', 10360)
('Blondel père et fils', 10436)
("Bon app'", 10331)
("Bon app'", 10340)
("Bon app'", 10362)
('Bottom-Dollar Marketse', 10389)
('Bottom-Dollar Marketse', 10410)
('Bottom-Dollar Marketse', 10411)
('Bottom-Dollar Marketse', 10431)
('Bólido Comidas preparadas', 10326)
('Cactus Comidas para llevar', None)
('Cardinal', None)
('Centro comercial Moctezuma', 10259)
('Chop-suey Chinese', 10254)
('Chop-suey Chinese', 10370)
('Comércio Mineiro', 10290)
('Consolidated Holdings', 10435)
('Die Wandernde Kuh', 10301)
('Die Wandernde Kuh', 10312)
('Die Wandernde Kuh', 10348)
('Die Wandernde Kuh', 10356)
('Drachenblut Delikatessend', 10363)
('Drachenblut Delikatessend', 10391)
('Du monde entier', 10311)
('Eastern Connection', 10364)
('Eastern Connection', 10400)
('Ernst Handel', 10258)
('Ernst Handel', 10263)
('Ernst Handel', 10351)
('Ernst Handel', 10368)
('Ernst Handel', 10382)
('Ernst Handel', 10390)
('Ernst Handel', 10402)
('Ernst Handel', 10403)
('Ernst Handel', 10430)
('Ernst Handel', 10442)
('FISSA Fabrica Inter. Salchichas S.A.', None)
('Familia Arquibaldo', 10347)
('Familia Arquibaldo', 10386)
('Familia Arquibaldo', 10414)
('Folies gourmandes', 10408)
('Folk och fä HB', 10264)
('Folk och fä HB', 10327)
('Folk och fä HB', 10378)
('Folk och fä HB', 10434)
('France restauration', None)
('Franchi S.p.A.', 10422)
('Frankenversand', 10267)
('Frankenversand', 10337)
('Frankenversand', 10342)
('Frankenversand', 10396)
('Furia Bacalhau e Frutos do Mar', 10328)
('Furia Bacalhau e Frutos do Mar', 10352)
('GROSELLA-Restaurante', 10268)
('Galería del gastrónomo', 10366)
('Galería del gastrónomo', 10426)
('Godos Cocina Típica', 10303)
('Gourmet Lanchonetes', 10423)
('Greasy Burger', None)
('Great Lakes Food Market', None)
('HILARIÓN-Abastos', 10257)
('HILARIÓN-Abastos', 10395)
('Hanari Carnes', 10250)
('Hanari Carnes', 10253)
('Hungry Coyote Import Store', 10375)
('Hungry Coyote Import Store', 10394)
('Hungry Coyote Import Store', 10415)
('Hungry Owl All-Night Grocers', 10298)
('Hungry Owl All-Night Grocers', 10309)
('Hungry Owl All-Night Grocers', 10335)
('Hungry Owl All-Night Grocers', 10373)
('Hungry Owl All-Night Grocers', 10380)
('Hungry Owl All-Night Grocers', 10429)
('Island Trading', 10315)
('Island Trading', 10318)
('Island Trading', 10321)
('Königlich Essen', 10323)
('Königlich Essen', 10325)
('LILA-Supermercado', 10283)
('LILA-Supermercado', 10296)
('LILA-Supermercado', 10330)
('LILA-Supermercado', 10357)
('LILA-Supermercado', 10381)
('LINO-Delicateses', 10405)
("La corne d'abondance", None)
("La maison d'Asie", 10350)
("La maison d'Asie", 10358)
("La maison d'Asie", 10371)
("La maison d'Asie", 10413)
("La maison d'Asie", 10425)
('Laughing Bacchus Wine Cellars', None)
('Lazy K Kountry Store', None)
('Lehmanns Marktstand', 10279)
('Lehmanns Marktstand', 10284)
('Lehmanns Marktstand', 10343)
("Let's Stop N Shop", None)
('Lonesome Pine Restaurant', 10307)
('Lonesome Pine Restaurant', 10317)
('Magazzini Alimentari Riuniti', 10275)
('Magazzini Alimentari Riuniti', 10300)
('Magazzini Alimentari Riuniti', 10404)
('Maison Dewey', None)
('Morgenstern Gesundkost', 10277)
('Mère Paillarde', 10332)
('Mère Paillarde', 10339)
('Mère Paillarde', 10376)
('Mère Paillarde', 10424)
('Mère Paillarde', 10439)
('North/South', None)
('Océano Atlántico Ltda.', 10409)
('Old World Delicatessen', 10260)
('Old World Delicatessen', 10305)
('Old World Delicatessen', 10338)
('Old World Delicatessen', 10441)
('Ottilies Käseladen', 10407)
('Paris spécialités', None)
('Pericles Comidas clásicas', 10322)
('Pericles Comidas clásicas', 10354)
('Piccolo und mehr', 10353)
('Piccolo und mehr', 10392)
('Piccolo und mehr', 10427)
('Princesa Isabel Vinhoss', 10336)
('Princesa Isabel Vinhoss', 10397)
('Princesa Isabel Vinhoss', 10433)
('QUICK-Stop', 10273)
('QUICK-Stop', 10285)
('QUICK-Stop', 10286)
('QUICK-Stop', 10313)
('QUICK-Stop', 10345)
('QUICK-Stop', 10361)
('QUICK-Stop', 10418)
('Que Delícia', 10261)
('Que Delícia', 10291)
('Que Delícia', 10379)
('Que Delícia', 10421)
('Queen Cozinha', 10372)
('Queen Cozinha', 10406)
('Rancho grande', None)
('Rattlesnake Canyon Grocery', 10262)
('Rattlesnake Canyon Grocery', 10272)
('Rattlesnake Canyon Grocery', 10294)
('Rattlesnake Canyon Grocery', 10314)
('Rattlesnake Canyon Grocery', 10316)
('Rattlesnake Canyon Grocery', 10346)
('Rattlesnake Canyon Grocery', 10401)
('Reggiani Caseifici', 10288)
('Reggiani Caseifici', 10428)
('Reggiani Caseifici', 10443)
('Ricardo Adocicados', 10287)
('Ricardo Adocicados', 10299)
('Richter Supermarkt', 10255)
('Richter Supermarkt', 10419)
('Romero y tomillo', 10281)
('Romero y tomillo', 10282)
('Romero y tomillo', 10306)
('Santé Gourmet', 10387)
('Save-a-lot Markets', 10324)
('Save-a-lot Markets', 10393)
('Save-a-lot Markets', 10398)
('Save-a-lot Markets', 10440)
('Seven Seas Imports', 10359)
('Seven Seas Imports', 10377)
('Seven Seas Imports', 10388)
('Simons bistro', 10341)
('Simons bistro', 10417)
('Split Rail Beer & Ale', 10271)
('Split Rail Beer & Ale', 10329)
('Split Rail Beer & Ale', 10349)
('Split Rail Beer & Ale', 10369)
('Split Rail Beer & Ale', 10385)
('Split Rail Beer & Ale', 10432)
('Spécialités du monde', None)
('Suprêmes délices', 10252)
('Suprêmes délices', 10302)
('Tasty Tee', None)
('The Big Cheese', 10310)
('The Cracker Box', None)
('Toms Spezialitäten', 10438)
('Tortuga Restaurante', 10276)
('Tortuga Restaurante', 10293)
('Tortuga Restaurante', 10304)
('Tortuga Restaurante', 10319)
('Tradição Hipermercados', 10249)
('Tradição Hipermercados', 10292)
("Trail's Head Gourmet Provisioners", None)
('Vaffeljernet', 10367)
('Vaffeljernet', 10399)
('Victuailles en stock', 10251)
('Victuailles en stock', 10334)
('Vins et alcools Chevalier', 10274)
('Vins et alcools Chevalier', 10295)
('Wartian Herkku', 10266)
('Wartian Herkku', 10270)
('Wartian Herkku', 10320)
('Wartian Herkku', 10333)
('Wartian Herkku', 10412)
('Wartian Herkku', 10416)
('Wartian Herkku', 10437)
('Wellington Importadora', 10256)
('Wellington Importadora', 10420)
('White Clover Markets', 10269)
('White Clover Markets', 10344)
('Wilman Kala', 10248)
('Wolski', 10374)

### RIGHT 조인

In [77]:

cursor = conn.cursor()
query = ''' 
SELECT Orders.OrderID, Employees.LastName, Employees.FirstName
FROM Orders
RIGHT JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID
ORDER BY Orders.OrderID;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['OrderID', 'LastName', 'FirstName']
(None, 'West', 'Adam')
(10248, 'Buchanan', 'Steven')
(10249, 'Suyama', 'Michael')
(10250, 'Peacock', 'Margaret')
(10251, 'Leverling', 'Janet')
(10252, 'Peacock', 'Margaret')
(10253, 'Leverling', 'Janet')
(10254, 'Buchanan', 'Steven')
(10255, 'Dodsworth', 'Anne')
(10256, 'Leverling', 'Janet')
(10257, 'Peacock', 'Margaret')
(10258, 'Davolio', 'Nancy')
(10259, 'Peacock', 'Margaret')
(10260, 'Peacock', 'Margaret')
(10261, 'Peacock', 'Margaret')
(10262, 'Callahan', 'Laura')
(10263, 'Dodsworth', 'Anne')
(10264, 'Suyama', 'Michael')
(10265, 'Fuller', 'Andrew')
(10266, 'Leverling', 'Janet')
(10267, 'Peacock', 'Margaret')
(10268, 'Callahan', 'Laura')
(10269, 'Buchanan', 'Steven')
(10270, 'Davolio', 'Nancy')
(10271, 'Suyama', 'Michael')
(10272, 'Suyama', 'Michael')
(10273, 'Leverling', 'Janet')
(10274, 'Suyama', 'Michael')
(10275, 'Davolio', 'Nancy')
(10276, 'Callahan', 'Laura')
(10277, 'Fuller', 'Andrew')
(10278, 'Callahan', 'Laura')
(10279, 'Callahan', 'Laura')
(10280, 'Fuller', 'Andrew')
(10281, 'Peacock', 'Margaret')
(10282, 'Peacock', 'Margaret')
(10283, 'Leverling', 'Janet')
(10284, 'Peacock', 'Margaret')
(10285, 'Davolio', 'Nancy')
(10286, 'Callahan', 'Laura')
(10287, 'Callahan', 'Laura')
(10288, 'Peacock', 'Margaret')
(10289, 'King', 'Robert')
(10290, 'Callahan', 'Laura')
(10291, 'Suyama', 'Michael')
(10292, 'Davolio', 'Nancy')
(10293, 'Davolio', 'Nancy')
(10294, 'Peacock', 'Margaret')
(10295, 'Fuller', 'Andrew')
(10296, 'Suyama', 'Michael')
(10297, 'Buchanan', 'Steven')
(10298, 'Suyama', 'Michael')
(10299, 'Peacock', 'Margaret')
(10300, 'Fuller', 'Andrew')
(10301, 'Callahan', 'Laura')
(10302, 'Peacock', 'Margaret')
(10303, 'King', 'Robert')
(10304, 'Davolio', 'Nancy')
(10305, 'Callahan', 'Laura')
(10306, 'Davolio', 'Nancy')
(10307, 'Fuller', 'Andrew')
(10308, 'King', 'Robert')
(10309, 'Leverling', 'Janet')
(10310, 'Callahan', 'Laura')
(10311, 'Davolio', 'Nancy')
(10312, 'Fuller', 'Andrew')
(10313, 'Fuller', 'Andrew')
(10314, 'Davolio', 'Nancy')
(10315, 'Peacock', 'Margaret')
(10316, 'Davolio', 'Nancy')
(10317, 'Suyama', 'Michael')
(10318, 'Callahan', 'Laura')
(10319, 'King', 'Robert')
(10320, 'Buchanan', 'Steven')
(10321, 'Leverling', 'Janet')
(10322, 'King', 'Robert')
(10323, 'Peacock', 'Margaret')
(10324, 'Dodsworth', 'Anne')
(10325, 'Davolio', 'Nancy')
(10326, 'Peacock', 'Margaret')
(10327, 'Fuller', 'Andrew')
(10328, 'Peacock', 'Margaret')
(10329, 'Peacock', 'Margaret')
(10330, 'Leverling', 'Janet')
(10331, 'Dodsworth', 'Anne')
(10332, 'Leverling', 'Janet')
(10333, 'Buchanan', 'Steven')
(10334, 'Callahan', 'Laura')
(10335, 'King', 'Robert')
(10336, 'King', 'Robert')
(10337, 'Peacock', 'Margaret')
(10338, 'Peacock', 'Margaret')
(10339, 'Fuller', 'Andrew')
(10340, 'Davolio', 'Nancy')
(10341, 'King', 'Robert')
(10342, 'Peacock', 'Margaret')
(10343, 'Peacock', 'Margaret')
(10344, 'Peacock', 'Margaret')
(10345, 'Fuller', 'Andrew')
(10346, 'Leverling', 'Janet')
(10347, 'Peacock', 'Margaret')
(10348, 'Peacock', 'Margaret')
(10349, 'King', 'Robert')
(10350, 'Suyama', 'Michael')
(10351, 'Davolio', 'Nancy')
(10352, 'Leverling', 'Janet')
(10353, 'King', 'Robert')
(10354, 'Callahan', 'Laura')
(10355, 'Suyama', 'Michael')
(10356, 'Suyama', 'Michael')
(10357, 'Davolio', 'Nancy')
(10358, 'Buchanan', 'Steven')
(10359, 'Buchanan', 'Steven')
(10360, 'Peacock', 'Margaret')
(10361, 'Davolio', 'Nancy')
(10362, 'Leverling', 'Janet')
(10363, 'Peacock', 'Margaret')
(10364, 'Davolio', 'Nancy')
(10365, 'Leverling', 'Janet')
(10366, 'Callahan', 'Laura')
(10367, 'King', 'Robert')
(10368, 'Fuller', 'Andrew')
(10369, 'Callahan', 'Laura')
(10370, 'Suyama', 'Michael')
(10371, 'Davolio', 'Nancy')
(10372, 'Buchanan', 'Steven')
(10373, 'Peacock', 'Margaret')
(10374, 'Davolio', 'Nancy')
(10375, 'Leverling', 'Janet')
(10376, 'Davolio', 'Nancy')
(10377, 'Davolio', 'Nancy')
(10378, 'Buchanan', 'Steven')
(10379, 'Fuller', 'Andrew')
(10380, 'Callahan', 'Laura')
(10381, 'Leverling', 'Janet')
(10382, 'Peacock', 'Margaret')
(10383, 'Callahan', 'Laura')
(10384, 'Leverling', 'Janet')
(10385, 'Davolio', 'Nancy')
(10386, 'Dodsworth', 'Anne')
(10387, 'Davolio', 'Nancy')
(10388, 'Fuller', 'Andrew')
(10389, 'Peacock', 'Margaret')
(10390, 'Suyama', 'Michael')
(10391, 'Leverling', 'Janet')
(10392, 'Fuller', 'Andrew')
(10393, 'Davolio', 'Nancy')
(10394, 'Davolio', 'Nancy')
(10395, 'Suyama', 'Michael')
(10396, 'Davolio', 'Nancy')
(10397, 'Buchanan', 'Steven')
(10398, 'Fuller', 'Andrew')
(10399, 'Callahan', 'Laura')
(10400, 'Davolio', 'Nancy')
(10401, 'Davolio', 'Nancy')
(10402, 'Callahan', 'Laura')
(10403, 'Peacock', 'Margaret')
(10404, 'Fuller', 'Andrew')
(10405, 'Davolio', 'Nancy')
(10406, 'King', 'Robert')
(10407, 'Fuller', 'Andrew')
(10408, 'Callahan', 'Laura')
(10409, 'Leverling', 'Janet')
(10410, 'Leverling', 'Janet')
(10411, 'Dodsworth', 'Anne')
(10412, 'Callahan', 'Laura')
(10413, 'Leverling', 'Janet')
(10414, 'Fuller', 'Andrew')
(10415, 'Leverling', 'Janet')
(10416, 'Callahan', 'Laura')
(10417, 'Peacock', 'Margaret')
(10418, 'Peacock', 'Margaret')
(10419, 'Peacock', 'Margaret')
(10420, 'Leverling', 'Janet')
(10421, 'Callahan', 'Laura')
(10422, 'Fuller', 'Andrew')
(10423, 'Suyama', 'Michael')
(10424, 'King', 'Robert')
(10425, 'Suyama', 'Michael')
(10426, 'Peacock', 'Margaret')
(10427, 'Peacock', 'Margaret')
(10428, 'King', 'Robert')
(10429, 'Leverling', 'Janet')
(10430, 'Peacock', 'Margaret')
(10431, 'Peacock', 'Margaret')
(10432, 'Leverling', 'Janet')
(10433, 'Leverling', 'Janet')
(10434, 'Leverling', 'Janet')
(10435, 'Callahan', 'Laura')
(10436, 'Leverling', 'Janet')
(10437, 'Callahan', 'Laura')
(10438, 'Leverling', 'Janet')
(10439, 'Suyama', 'Michael')
(10440, 'Peacock', 'Margaret')
(10441, 'Leverling', 'Janet')
(10442, 'Leverling', 'Janet')
(10443, 'Callahan', 'Laura')

### 전체조인 FULL OUTER

In [78]:

cursor = conn.cursor()
query = ''' 
SELECT Customers.CustomerName, Orders.OrderID
FROM Customers
FULL OUTER JOIN Orders ON Customers.CustomerID=Orders.CustomerID
ORDER BY Customers.CustomerName;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerName', 'OrderID']
('Alfreds Futterkiste', None)
('Ana Trujillo Emparedados y helados', 10308)
('Antonio Moreno Taquería', 10365)
('Around the Horn', 10355)
('Around the Horn', 10383)
("B's Beverages", 10289)
('Berglunds snabbköp', 10278)
('Berglunds snabbköp', 10280)
('Berglunds snabbköp', 10384)
('Blauer See Delikatessen', None)
('Blondel père et fils', 10265)
('Blondel père et fils', 10297)
('Blondel père et fils', 10360)
('Blondel père et fils', 10436)
("Bon app'", 10331)
("Bon app'", 10340)
("Bon app'", 10362)
('Bottom-Dollar Marketse', 10389)
('Bottom-Dollar Marketse', 10410)
('Bottom-Dollar Marketse', 10411)
('Bottom-Dollar Marketse', 10431)
('Bólido Comidas preparadas', 10326)
('Cactus Comidas para llevar', None)
('Cardinal', None)
('Centro comercial Moctezuma', 10259)
('Chop-suey Chinese', 10254)
('Chop-suey Chinese', 10370)
('Comércio Mineiro', 10290)
('Consolidated Holdings', 10435)
('Die Wandernde Kuh', 10301)
('Die Wandernde Kuh', 10312)
('Die Wandernde Kuh', 10348)
('Die Wandernde Kuh', 10356)
('Drachenblut Delikatessend', 10363)
('Drachenblut Delikatessend', 10391)
('Du monde entier', 10311)
('Eastern Connection', 10364)
('Eastern Connection', 10400)
('Ernst Handel', 10258)
('Ernst Handel', 10263)
('Ernst Handel', 10351)
('Ernst Handel', 10368)
('Ernst Handel', 10382)
('Ernst Handel', 10390)
('Ernst Handel', 10402)
('Ernst Handel', 10403)
('Ernst Handel', 10430)
('Ernst Handel', 10442)
('FISSA Fabrica Inter. Salchichas S.A.', None)
('Familia Arquibaldo', 10347)
('Familia Arquibaldo', 10386)
('Familia Arquibaldo', 10414)
('Folies gourmandes', 10408)
('Folk och fä HB', 10264)
('Folk och fä HB', 10327)
('Folk och fä HB', 10378)
('Folk och fä HB', 10434)
('France restauration', None)
('Franchi S.p.A.', 10422)
('Frankenversand', 10267)
('Frankenversand', 10337)
('Frankenversand', 10342)
('Frankenversand', 10396)
('Furia Bacalhau e Frutos do Mar', 10328)
('Furia Bacalhau e Frutos do Mar', 10352)
('GROSELLA-Restaurante', 10268)
('Galería del gastrónomo', 10366)
('Galería del gastrónomo', 10426)
('Godos Cocina Típica', 10303)
('Gourmet Lanchonetes', 10423)
('Greasy Burger', None)
('Great Lakes Food Market', None)
('HILARIÓN-Abastos', 10257)
('HILARIÓN-Abastos', 10395)
('Hanari Carnes', 10250)
('Hanari Carnes', 10253)
('Hungry Coyote Import Store', 10375)
('Hungry Coyote Import Store', 10394)
('Hungry Coyote Import Store', 10415)
('Hungry Owl All-Night Grocers', 10298)
('Hungry Owl All-Night Grocers', 10309)
('Hungry Owl All-Night Grocers', 10335)
('Hungry Owl All-Night Grocers', 10373)
('Hungry Owl All-Night Grocers', 10380)
('Hungry Owl All-Night Grocers', 10429)
('Island Trading', 10315)
('Island Trading', 10318)
('Island Trading', 10321)
('Königlich Essen', 10323)
('Königlich Essen', 10325)
('LILA-Supermercado', 10283)
('LILA-Supermercado', 10296)
('LILA-Supermercado', 10330)
('LILA-Supermercado', 10357)
('LILA-Supermercado', 10381)
('LINO-Delicateses', 10405)
("La corne d'abondance", None)
("La maison d'Asie", 10350)
("La maison d'Asie", 10358)
("La maison d'Asie", 10371)
("La maison d'Asie", 10413)
("La maison d'Asie", 10425)
('Laughing Bacchus Wine Cellars', None)
('Lazy K Kountry Store', None)
('Lehmanns Marktstand', 10279)
('Lehmanns Marktstand', 10284)
('Lehmanns Marktstand', 10343)
("Let's Stop N Shop", None)
('Lonesome Pine Restaurant', 10307)
('Lonesome Pine Restaurant', 10317)
('Magazzini Alimentari Riuniti', 10275)
('Magazzini Alimentari Riuniti', 10300)
('Magazzini Alimentari Riuniti', 10404)
('Maison Dewey', None)
('Morgenstern Gesundkost', 10277)
('Mère Paillarde', 10332)
('Mère Paillarde', 10339)
('Mère Paillarde', 10376)
('Mère Paillarde', 10424)
('Mère Paillarde', 10439)
('North/South', None)
('Océano Atlántico Ltda.', 10409)
('Old World Delicatessen', 10260)
('Old World Delicatessen', 10305)
('Old World Delicatessen', 10338)
('Old World Delicatessen', 10441)
('Ottilies Käseladen', 10407)
('Paris spécialités', None)
('Pericles Comidas clásicas', 10322)
('Pericles Comidas clásicas', 10354)
('Piccolo und mehr', 10353)
('Piccolo und mehr', 10392)
('Piccolo und mehr', 10427)
('Princesa Isabel Vinhoss', 10336)
('Princesa Isabel Vinhoss', 10397)
('Princesa Isabel Vinhoss', 10433)
('QUICK-Stop', 10273)
('QUICK-Stop', 10285)
('QUICK-Stop', 10286)
('QUICK-Stop', 10313)
('QUICK-Stop', 10345)
('QUICK-Stop', 10361)
('QUICK-Stop', 10418)
('Que Delícia', 10261)
('Que Delícia', 10291)
('Que Delícia', 10379)
('Que Delícia', 10421)
('Queen Cozinha', 10372)
('Queen Cozinha', 10406)
('Rancho grande', None)
('Rattlesnake Canyon Grocery', 10262)
('Rattlesnake Canyon Grocery', 10272)
('Rattlesnake Canyon Grocery', 10294)
('Rattlesnake Canyon Grocery', 10314)
('Rattlesnake Canyon Grocery', 10316)
('Rattlesnake Canyon Grocery', 10346)
('Rattlesnake Canyon Grocery', 10401)
('Reggiani Caseifici', 10288)
('Reggiani Caseifici', 10428)
('Reggiani Caseifici', 10443)
('Ricardo Adocicados', 10287)
('Ricardo Adocicados', 10299)
('Richter Supermarkt', 10255)
('Richter Supermarkt', 10419)
('Romero y tomillo', 10281)
('Romero y tomillo', 10282)
('Romero y tomillo', 10306)
('Santé Gourmet', 10387)
('Save-a-lot Markets', 10324)
('Save-a-lot Markets', 10393)
('Save-a-lot Markets', 10398)
('Save-a-lot Markets', 10440)
('Seven Seas Imports', 10359)
('Seven Seas Imports', 10377)
('Seven Seas Imports', 10388)
('Simons bistro', 10341)
('Simons bistro', 10417)
('Split Rail Beer & Ale', 10271)
('Split Rail Beer & Ale', 10329)
('Split Rail Beer & Ale', 10349)
('Split Rail Beer & Ale', 10369)
('Split Rail Beer & Ale', 10385)
('Split Rail Beer & Ale', 10432)
('Spécialités du monde', None)
('Suprêmes délices', 10252)
('Suprêmes délices', 10302)
('Tasty Tee', None)
('The Big Cheese', 10310)
('The Cracker Box', None)
('Toms Spezialitäten', 10438)
('Tortuga Restaurante', 10276)
('Tortuga Restaurante', 10293)
('Tortuga Restaurante', 10304)
('Tortuga Restaurante', 10319)
('Tradição Hipermercados', 10249)
('Tradição Hipermercados', 10292)
("Trail's Head Gourmet Provisioners", None)
('Vaffeljernet', 10367)
('Vaffeljernet', 10399)
('Victuailles en stock', 10251)
('Victuailles en stock', 10334)
('Vins et alcools Chevalier', 10274)
('Vins et alcools Chevalier', 10295)
('Wartian Herkku', 10266)
('Wartian Herkku', 10270)
('Wartian Herkku', 10320)
('Wartian Herkku', 10333)
('Wartian Herkku', 10412)
('Wartian Herkku', 10416)
('Wartian Herkku', 10437)
('Wellington Importadora', 10256)
('Wellington Importadora', 10420)
('White Clover Markets', 10269)
('White Clover Markets', 10344)
('Wilman Kala', 10248)
('Wolski', 10374)

#### self join

In [79]:

cursor = conn.cursor()
query = ''' 
SELECT A.CustomerName AS CustomerName1, B.CustomerName AS CustomerName2, A.City
FROM Customers A, Customers B
WHERE A.CustomerID <> B.CustomerID
AND A.City = B.City
ORDER BY A.City;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerName1', 'CustomerName2', 'City']
('Cactus Comidas para llevar', 'Océano Atlántico Ltda.', 'Buenos Aires')
('Cactus Comidas para llevar', 'Rancho grande', 'Buenos Aires')
('Océano Atlántico Ltda.', 'Cactus Comidas para llevar', 'Buenos Aires')
('Océano Atlántico Ltda.', 'Rancho grande', 'Buenos Aires')
('Rancho grande', 'Cactus Comidas para llevar', 'Buenos Aires')
('Rancho grande', 'Océano Atlántico Ltda.', 'Buenos Aires')
('Furia Bacalhau e Frutos do Mar', 'Princesa Isabel Vinhoss', 'Lisboa')
('Princesa Isabel Vinhoss', 'Furia Bacalhau e Frutos do Mar', 'Lisboa')
('Around the Horn', "B's Beverages", 'London')
('Around the Horn', 'Consolidated Holdings', 'London')
('Around the Horn', 'Eastern Connection', 'London')
('Around the Horn', 'North/South', 'London')
('Around the Horn', 'Seven Seas Imports', 'London')
("B's Beverages", 'Around the Horn', 'London')
("B's Beverages", 'Consolidated Holdings', 'London')
("B's Beverages", 'Eastern Connection', 'London')
("B's Beverages", 'North/South', 'London')
("B's Beverages", 'Seven Seas Imports', 'London')
('Consolidated Holdings', 'Around the Horn', 'London')
('Consolidated Holdings', "B's Beverages", 'London')
('Consolidated Holdings', 'Eastern Connection', 'London')
('Consolidated Holdings', 'North/South', 'London')
('Consolidated Holdings', 'Seven Seas Imports', 'London')
('Eastern Connection', 'Around the Horn', 'London')
('Eastern Connection', "B's Beverages", 'London')
('Eastern Connection', 'Consolidated Holdings', 'London')
('Eastern Connection', 'North/South', 'London')
('Eastern Connection', 'Seven Seas Imports', 'London')
('North/South', 'Around the Horn', 'London')
('North/South', "B's Beverages", 'London')
('North/South', 'Consolidated Holdings', 'London')
('North/South', 'Eastern Connection', 'London')
('North/South', 'Seven Seas Imports', 'London')
('Seven Seas Imports', 'Around the Horn', 'London')
('Seven Seas Imports', "B's Beverages", 'London')
('Seven Seas Imports', 'Consolidated Holdings', 'London')
('Seven Seas Imports', 'Eastern Connection', 'London')
('Seven Seas Imports', 'North/South', 'London')
('Bólido Comidas preparadas', 'FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Bólido Comidas preparadas', 'Romero y tomillo', 'Madrid')
('FISSA Fabrica Inter. Salchichas S.A.', 'Bólido Comidas preparadas', 'Madrid')
('FISSA Fabrica Inter. Salchichas S.A.', 'Romero y tomillo', 'Madrid')
('Romero y tomillo', 'Bólido Comidas preparadas', 'Madrid')
('Romero y tomillo', 'FISSA Fabrica Inter. Salchichas S.A.', 'Madrid')
('Ana Trujillo Emparedados y helados', 'Antonio Moreno Taquería', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Centro comercial Moctezuma', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Pericles Comidas clásicas', 'México D.F.')
('Ana Trujillo Emparedados y helados', 'Tortuga Restaurante', 'México D.F.')
('Antonio Moreno Taquería', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Antonio Moreno Taquería', 'Centro comercial Moctezuma', 'México D.F.')
('Antonio Moreno Taquería', 'Pericles Comidas clásicas', 'México D.F.')
('Antonio Moreno Taquería', 'Tortuga Restaurante', 'México D.F.')
('Centro comercial Moctezuma', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Centro comercial Moctezuma', 'Antonio Moreno Taquería', 'México D.F.')
('Centro comercial Moctezuma', 'Pericles Comidas clásicas', 'México D.F.')
('Centro comercial Moctezuma', 'Tortuga Restaurante', 'México D.F.')
('Pericles Comidas clásicas', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Pericles Comidas clásicas', 'Antonio Moreno Taquería', 'México D.F.')
('Pericles Comidas clásicas', 'Centro comercial Moctezuma', 'México D.F.')
('Pericles Comidas clásicas', 'Tortuga Restaurante', 'México D.F.')
('Tortuga Restaurante', 'Ana Trujillo Emparedados y helados', 'México D.F.')
('Tortuga Restaurante', 'Antonio Moreno Taquería', 'México D.F.')
('Tortuga Restaurante', 'Centro comercial Moctezuma', 'México D.F.')
('Tortuga Restaurante', 'Pericles Comidas clásicas', 'México D.F.')
('Du monde entier', 'France restauration', 'Nantes')
('France restauration', 'Du monde entier', 'Nantes')
('Paris spécialités', 'Spécialités du monde', 'Paris')
('Spécialités du monde', 'Paris spécialités', 'Paris')
('Lonesome Pine Restaurant', 'The Big Cheese', 'Portland')
('The Big Cheese', 'Lonesome Pine Restaurant', 'Portland')
('Hanari Carnes', 'Que Delícia', 'Rio de Janeiro')
('Hanari Carnes', 'Ricardo Adocicados', 'Rio de Janeiro')
('Que Delícia', 'Hanari Carnes', 'Rio de Janeiro')
('Que Delícia', 'Ricardo Adocicados', 'Rio de Janeiro')
('Ricardo Adocicados', 'Hanari Carnes', 'Rio de Janeiro')
('Ricardo Adocicados', 'Que Delícia', 'Rio de Janeiro')
('Comércio Mineiro', 'Familia Arquibaldo', 'São Paulo')
('Comércio Mineiro', 'Queen Cozinha', 'São Paulo')
('Comércio Mineiro', 'Tradição Hipermercados', 'São Paulo')
('Familia Arquibaldo', 'Comércio Mineiro', 'São Paulo')
('Familia Arquibaldo', 'Queen Cozinha', 'São Paulo')
('Familia Arquibaldo', 'Tradição Hipermercados', 'São Paulo')
('Queen Cozinha', 'Comércio Mineiro', 'São Paulo')
('Queen Cozinha', 'Familia Arquibaldo', 'São Paulo')
('Queen Cozinha', 'Tradição Hipermercados', 'São Paulo')
('Tradição Hipermercados', 'Comércio Mineiro', 'São Paulo')
('Tradição Hipermercados', 'Familia Arquibaldo', 'São Paulo')
('Tradição Hipermercados', 'Queen Cozinha', 'São Paulo')

#### UNION 고유값

In [80]:

cursor = conn.cursor()
query = ''' 
SELECT City FROM Customers
UNION
SELECT City FROM Suppliers
ORDER BY City;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['City']
('Aachen',)
('Albuquerque',)
('Anchorage',)
('Ann Arbor',)
('Annecy',)
('Barcelona',)
('Barquisimeto',)
('Bend',)
('Bergamo',)
('Berlin',)
('Bern',)
('Boise',)
('Boston',)
('Brandenburg',)
('Bruxelles',)
('Bräcke',)
('Buenos Aires',)
('Butte',)
('Campinas',)
('Caracas',)
('Charleroi',)
('Cork',)
('Cowes',)
('Cunewalde',)
('Cuxhaven',)
('Elgin',)
('Eugene',)
('Frankfurt',)
('Frankfurt a.M. ',)
('Genève',)
('Graz',)
('Göteborg',)
('Helsinki',)
('I. de Margarita',)
('Kirkland',)
('Köln',)
('København',)
('Lander',)
('Lappeenranta',)
('Leipzig',)
('Lille',)
('Lisboa',)
('Liverpool',)
('London',)
('Londona',)
('Luleå',)
('Lyngby',)
('Lyon',)
('Madrid',)
('Manchester',)
('Mannheim',)
('Marseille',)
('Melbourne',)
('Montceau',)
('Montréal',)
('México D.F.',)
('München',)
('Münster',)
('Nantes',)
('New Orleans',)
('Osaka',)
('Oulu',)
('Oviedo',)
('Paris',)
('Portland',)
('Ravenna',)
('Reggio Emilia',)
('Reims',)
('Resende',)
('Rio de Janeiro',)
('Salerno',)
('Salzburg',)
('San Cristóbal',)
('San Francisco',)
('Sandnes',)
('Sandvika',)
('Seattle',)
('Sevilla',)
('Singapore',)
('Stavanger',)
('Stavern',)
('Ste-Hyacinthe',)
('Stockholm',)
('Strasbourg',)
('Stuttgart',)
('Sydney',)
('São Paulo',)
('Tokyo',)
('Torino',)
('Toulouse',)
('Tsawassen',)
('Vancouver',)
('Versailles',)
('Walla',)
('Walla Walla',)
('Zaandam',)
('Århus',)

# GROUP BY

In [81]:

cursor = conn.cursor()
query = ''' 
SELECT COUNT(CustomerID), Country
FROM Customers
GROUP BY Country;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['COUNT(CustomerID)', 'Country']
(1, None)
(3, 'Argentina')
(2, 'Austria')
(2, 'Belgium')
(9, 'Brazil')
(3, 'Canada')
(2, 'Denmark')
(2, 'Finland')
(11, 'France')
(11, 'Germany')
(1, 'Ireland')
(3, 'Italy')
(5, 'Mexico')
(1, 'Norway')
(2, 'Portugal')
(5, 'Spain')
(2, 'Sweden')
(2, 'Switzerland')
(7, 'UK')
(13, 'USA')
(4, 'Venezuela')

### HAVING

In [82]:

cursor = conn.cursor()
query = ''' 
SELECT COUNT(CustomerID), Country
FROM Customers
GROUP BY Country
HAVING COUNT(CustomerID) > 5
ORDER BY COUNT(CustomerID) DESC;
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['COUNT(CustomerID)', 'Country']
(13, 'USA')
(11, 'Germany')
(11, 'France')
(9, 'Brazil')
(7, 'UK')

### EXISTS 하위쿼리에 레코드가 존재하는지

In [83]:

cursor = conn.cursor()
query = ''' 
SELECT SupplierName
FROM Suppliers
WHERE EXISTS (
    SELECT ProductName 
    FROM Products WHERE Products.SupplierID = Suppliers.supplierID 
        AND Price < 20);
''' 

cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['SupplierName']
('Exotic Liquid',)
('New Orleans Cajun Delights',)
('Tokyo Traders',)
("Mayumi's",)
('Pavlova, Ltd.',)
('Specialty Biscuits, Ltd.',)
('PB Knäckebröd AB',)
('Refrescos Americanas LTDA',)
('Heli Süßwaren GmbH & Co. KG',)
('Plutzer Lebensmittelgroßmärkte AG',)
('Formaggi Fortini s.r.l.',)
('Norske Meierier',)
('Bigfoot Breweries',)
('Svensk Sjöföda AB',)
('Aux joyeux ecclésiastiques',)
('New England Seafood Cannery',)
('Leka Trading',)
('Lyngbysild',)
('Zaanse Snoepfabriek',)
('Karkki Oy',)
("G'day, Mate",)
('Ma Maison',)
('Pasta Buttini s.r.l.',)
('Escargots Nouveaux',)

### ANY -> IN

In [84]:

cursor = conn.cursor()
query = ''' 
SELECT ProductName
FROM Products
WHERE ProductID IN
  (SELECT ProductID
   FROM OrderDetails
   WHERE Quantity = 10)
'''
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['ProductName']
('Chais',)
('Chang',)
("Chef Anton's Cajun Seasoning",)
("Uncle Bob's Organic Dried Pears",)
('Konbu',)
('Tofu',)
('Pavlova',)
('Teatime Chocolate Biscuits',)
("Sir Rodney's Scones",)
('Guaraná Fantástica',)
('NuNuCa Nuß-Nougat-Creme',)
('Gumbär Gummibärchen',)
('Thüringer Rostbratwurst',)
('Nord-Ost Matjeshering',)
('Sasquatch Ale',)
('Steeleye Stout',)
('Gravad lax',)
('Côte de Blaye',)
('Boston Crab Meat',)
("Jack's New England Clam Chowder",)
('Singaporean Hokkien Fried Mee',)
('Perth Pasties',)
('Tourtière',)
('Pâté chinois',)
('Raclette Courdavault',)
('Tarte au sucre',)
('Louisiana Fiery Hot Pepper Sauce',)
('Scottish Longbreads',)
('Mozzarella di Giovanni',)
('Rhönbräu Klosterbier',)
('Original Frankfurter grüne Soße',)

###  INSERT INTO

In [85]:

cursor = conn.cursor()
query = ''' 
INSERT INTO Customers (CustomerName, City, Country)
SELECT SupplierName, City, Country
FROM Suppliers
'''

cursor.execute(query)
conn.commit()

# SQL 쿼리 실행하여 데이터 가져오기
query = 'SELECT * FROM Customers'
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', None, 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)
(None, 'Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway')
(None, 'Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway')
(None, 'Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')
(None, 'Exotic Liquid', None, None, 'Londona', None, 'UK')
(None, 'New Orleans Cajun Delights', None, None, 'New Orleans', None, 'USA')
(None, "Grandma Kelly's Homestead", None, None, 'Ann Arbor', None, 'USA')
(None, 'Tokyo Traders', None, None, 'Tokyo', None, 'Japan')
(None, "Cooperativa de Quesos 'Las Cabras'", None, None, 'Oviedo', None, 'Spain')
(None, "Mayumi's", None, None, 'Osaka', None, 'Japan')
(None, 'Pavlova, Ltd.', None, None, 'Melbourne', None, 'Australia')
(None, 'Specialty Biscuits, Ltd.', None, None, 'Manchester', None, 'UK')
(None, 'PB Knäckebröd AB', None, None, 'Göteborg', None, 'Sweden ')
(None, 'Refrescos Americanas LTDA', None, None, 'São Paulo', None, 'Brazil')
(None, 'Heli Süßwaren GmbH & Co. KG', None, None, 'Berlin', None, 'Germany')
(None, 'Plutzer Lebensmittelgroßmärkte AG', None, None, 'Frankfurt', None, 'Germany')
(None, 'Nord-Ost-Fisch Handelsgesellschaft mbH', None, None, 'Cuxhaven', None, 'Germany')
(None, 'Formaggi Fortini s.r.l.', None, None, 'Ravenna', None, 'Italy')
(None, 'Norske Meierier', None, None, 'Sandvika', None, 'Norway')
(None, 'Bigfoot Breweries', None, None, 'Bend', None, 'USA')
(None, 'Svensk Sjöföda AB', None, None, 'Stockholm', None, 'Sweden')
(None, 'Aux joyeux ecclésiastiques', None, None, 'Paris', None, 'France')
(None, 'New England Seafood Cannery', None, None, 'Boston', None, 'USA')
(None, 'Leka Trading', None, None, 'Singapore', None, 'Singapore')
(None, 'Lyngbysild', None, None, 'Lyngby', None, 'Denmark')
(None, 'Zaanse Snoepfabriek', None, None, 'Zaandam', None, 'Netherlands')
(None, 'Karkki Oy', None, None, 'Lappeenranta', None, 'Finland')
(None, "G'day, Mate", None, None, 'Sydney', None, 'Australia')
(None, 'Ma Maison', None, None, 'Montréal', None, 'Canada')
(None, 'Pasta Buttini s.r.l.', None, None, 'Salerno', None, 'Italy')
(None, 'Escargots Nouveaux', None, None, 'Montceau', None, 'France')
(None, 'Gai pâturage', None, None, 'Annecy', None, 'France')
(None, "Forêts d'érables", None, None, 'Ste-Hyacinthe', None, 'Canada')

### CASE  조건을 거치고 첫 번째 조건이 충족되면 값을 반환 IF Then Else

In [86]:

cursor = conn.cursor()
query = ''' 
SELECT OrderID, Quantity,
CASE
    WHEN Quantity > 30 THEN 'The quantity is greater than 30'
    WHEN Quantity = 30 THEN 'The quantity is 30'
    ELSE 'The quantity is under 30'
END AS QuantityText
FROM OrderDetails;
'''
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['OrderID', 'Quantity', 'QuantityText']
(10248, 12, 'The quantity is under 30')
(10248, 10, 'The quantity is under 30')
(10248, 5, 'The quantity is under 30')
(10249, 9, 'The quantity is under 30')
(10249, 40, 'The quantity is greater than 30')
(10250, 10, 'The quantity is under 30')
(10250, 35, 'The quantity is greater than 30')
(10250, 15, 'The quantity is under 30')
(10251, 6, 'The quantity is under 30')
(10251, 15, 'The quantity is under 30')
(10251, 20, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10252, 25, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10253, 20, 'The quantity is under 30')
(10253, 42, 'The quantity is greater than 30')
(10253, 40, 'The quantity is greater than 30')
(10254, 15, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10255, 20, 'The quantity is under 30')
(10255, 35, 'The quantity is greater than 30')
(10255, 25, 'The quantity is under 30')
(10255, 30, 'The quantity is 30')
(10256, 15, 'The quantity is under 30')
(10256, 12, 'The quantity is under 30')
(10257, 25, 'The quantity is under 30')
(10257, 6, 'The quantity is under 30')
(10257, 15, 'The quantity is under 30')
(10258, 50, 'The quantity is greater than 30')
(10258, 65, 'The quantity is greater than 30')
(10258, 6, 'The quantity is under 30')
(10259, 10, 'The quantity is under 30')
(10259, 1, 'The quantity is under 30')
(10260, 16, 'The quantity is under 30')
(10260, 50, 'The quantity is greater than 30')
(10260, 15, 'The quantity is under 30')
(10260, 21, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10262, 12, 'The quantity is under 30')
(10262, 15, 'The quantity is under 30')
(10262, 2, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 28, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 36, 'The quantity is greater than 30')
(10264, 35, 'The quantity is greater than 30')
(10264, 25, 'The quantity is under 30')
(10265, 30, 'The quantity is 30')
(10265, 20, 'The quantity is under 30')
(10266, 12, 'The quantity is under 30')
(10267, 50, 'The quantity is greater than 30')
(10267, 70, 'The quantity is greater than 30')
(10267, 15, 'The quantity is under 30')
(10268, 10, 'The quantity is under 30')
(10268, 4, 'The quantity is under 30')
(10269, 60, 'The quantity is greater than 30')
(10269, 20, 'The quantity is under 30')
(10270, 30, 'The quantity is 30')
(10270, 25, 'The quantity is under 30')
(10271, 24, 'The quantity is under 30')
(10272, 6, 'The quantity is under 30')
(10272, 40, 'The quantity is greater than 30')
(10272, 24, 'The quantity is under 30')
(10273, 24, 'The quantity is under 30')
(10273, 15, 'The quantity is under 30')
(10273, 20, 'The quantity is under 30')
(10273, 60, 'The quantity is greater than 30')
(10273, 33, 'The quantity is greater than 30')
(10274, 20, 'The quantity is under 30')
(10274, 7, 'The quantity is under 30')
(10275, 12, 'The quantity is under 30')
(10275, 6, 'The quantity is under 30')
(10276, 15, 'The quantity is under 30')
(10276, 10, 'The quantity is under 30')
(10277, 20, 'The quantity is under 30')
(10277, 12, 'The quantity is under 30')
(10278, 16, 'The quantity is under 30')
(10278, 15, 'The quantity is under 30')
(10278, 8, 'The quantity is under 30')
(10278, 25, 'The quantity is under 30')
(10279, 15, 'The quantity is under 30')
(10280, 12, 'The quantity is under 30')
(10280, 20, 'The quantity is under 30')
(10280, 30, 'The quantity is 30')
(10281, 1, 'The quantity is under 30')
(10281, 6, 'The quantity is under 30')
(10281, 4, 'The quantity is under 30')
(10282, 6, 'The quantity is under 30')
(10282, 2, 'The quantity is under 30')
(10283, 20, 'The quantity is under 30')
(10283, 18, 'The quantity is under 30')
(10283, 35, 'The quantity is greater than 30')
(10283, 3, 'The quantity is under 30')
(10284, 15, 'The quantity is under 30')
(10284, 21, 'The quantity is under 30')
(10284, 20, 'The quantity is under 30')
(10284, 5, 'The quantity is under 30')
(10285, 45, 'The quantity is greater than 30')
(10285, 40, 'The quantity is greater than 30')
(10285, 36, 'The quantity is greater than 30')
(10286, 100, 'The quantity is greater than 30')
(10286, 40, 'The quantity is greater than 30')
(10287, 40, 'The quantity is greater than 30')
(10287, 20, 'The quantity is under 30')
(10287, 15, 'The quantity is under 30')
(10288, 10, 'The quantity is under 30')
(10288, 3, 'The quantity is under 30')
(10289, 30, 'The quantity is 30')
(10289, 9, 'The quantity is under 30')
(10290, 20, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 10, 'The quantity is under 30')
(10291, 20, 'The quantity is under 30')
(10291, 24, 'The quantity is under 30')
(10291, 2, 'The quantity is under 30')
(10292, 20, 'The quantity is under 30')
(10293, 12, 'The quantity is under 30')
(10293, 10, 'The quantity is under 30')
(10293, 5, 'The quantity is under 30')
(10293, 6, 'The quantity is under 30')
(10294, 18, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 21, 'The quantity is under 30')
(10294, 6, 'The quantity is under 30')
(10295, 4, 'The quantity is under 30')
(10296, 12, 'The quantity is under 30')
(10296, 30, 'The quantity is 30')
(10296, 15, 'The quantity is under 30')
(10297, 60, 'The quantity is greater than 30')
(10297, 20, 'The quantity is under 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 30, 'The quantity is 30')
(10298, 15, 'The quantity is under 30')
(10299, 15, 'The quantity is under 30')
(10299, 20, 'The quantity is under 30')
(10300, 30, 'The quantity is 30')
(10300, 20, 'The quantity is under 30')
(10301, 10, 'The quantity is under 30')
(10301, 20, 'The quantity is under 30')
(10302, 40, 'The quantity is greater than 30')
(10302, 28, 'The quantity is under 30')
(10302, 12, 'The quantity is under 30')
(10303, 40, 'The quantity is greater than 30')
(10303, 30, 'The quantity is 30')
(10303, 15, 'The quantity is under 30')
(10304, 30, 'The quantity is 30')
(10304, 10, 'The quantity is under 30')
(10304, 2, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 30, 'The quantity is 30')
(10306, 10, 'The quantity is under 30')
(10306, 10, 'The quantity is under 30')
(10306, 5, 'The quantity is under 30')
(10307, 10, 'The quantity is under 30')
(10307, 3, 'The quantity is under 30')
(10308, 1, 'The quantity is under 30')
(10308, 5, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 30, 'The quantity is 30')
(10309, 2, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 3, 'The quantity is under 30')
(10310, 10, 'The quantity is under 30')
(10310, 5, 'The quantity is under 30')
(10311, 6, 'The quantity is under 30')
(10311, 7, 'The quantity is under 30')
(10312, 4, 'The quantity is under 30')
(10312, 24, 'The quantity is under 30')
(10312, 20, 'The quantity is under 30')
(10312, 10, 'The quantity is under 30')
(10313, 12, 'The quantity is under 30')
(10314, 40, 'The quantity is greater than 30')
(10314, 30, 'The quantity is 30')
(10314, 25, 'The quantity is under 30')
(10315, 14, 'The quantity is under 30')
(10315, 30, 'The quantity is 30')
(10316, 10, 'The quantity is under 30')
(10316, 70, 'The quantity is greater than 30')
(10317, 20, 'The quantity is under 30')
(10318, 20, 'The quantity is under 30')
(10318, 6, 'The quantity is under 30')
(10319, 8, 'The quantity is under 30')
(10319, 14, 'The quantity is under 30')
(10319, 30, 'The quantity is 30')
(10320, 30, 'The quantity is 30')
(10321, 10, 'The quantity is under 30')
(10322, 20, 'The quantity is under 30')
(10323, 5, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10324, 21, 'The quantity is under 30')
(10324, 70, 'The quantity is greater than 30')
(10324, 30, 'The quantity is 30')
(10324, 40, 'The quantity is greater than 30')
(10324, 80, 'The quantity is greater than 30')
(10325, 6, 'The quantity is under 30')
(10325, 12, 'The quantity is under 30')
(10325, 9, 'The quantity is under 30')
(10325, 4, 'The quantity is under 30')
(10325, 40, 'The quantity is greater than 30')
(10326, 24, 'The quantity is under 30')
(10326, 16, 'The quantity is under 30')
(10326, 50, 'The quantity is greater than 30')
(10327, 25, 'The quantity is under 30')
(10327, 50, 'The quantity is greater than 30')
(10327, 35, 'The quantity is greater than 30')
(10327, 30, 'The quantity is 30')
(10328, 9, 'The quantity is under 30')
(10328, 40, 'The quantity is greater than 30')
(10328, 10, 'The quantity is under 30')
(10329, 10, 'The quantity is under 30')
(10329, 8, 'The quantity is under 30')
(10329, 20, 'The quantity is under 30')
(10329, 12, 'The quantity is under 30')
(10330, 50, 'The quantity is greater than 30')
(10330, 25, 'The quantity is under 30')
(10331, 15, 'The quantity is under 30')
(10332, 40, 'The quantity is greater than 30')
(10332, 10, 'The quantity is under 30')
(10332, 16, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 40, 'The quantity is greater than 30')
(10334, 8, 'The quantity is under 30')
(10334, 10, 'The quantity is under 30')
(10335, 7, 'The quantity is under 30')
(10335, 25, 'The quantity is under 30')
(10335, 6, 'The quantity is under 30')
(10335, 48, 'The quantity is greater than 30')
(10336, 18, 'The quantity is under 30')
(10337, 40, 'The quantity is greater than 30')
(10337, 24, 'The quantity is under 30')
(10337, 20, 'The quantity is under 30')
(10337, 28, 'The quantity is under 30')
(10337, 25, 'The quantity is under 30')
(10338, 20, 'The quantity is under 30')
(10338, 15, 'The quantity is under 30')
(10339, 10, 'The quantity is under 30')
(10339, 70, 'The quantity is greater than 30')
(10339, 28, 'The quantity is under 30')
(10340, 20, 'The quantity is under 30')
(10340, 12, 'The quantity is under 30')
(10340, 40, 'The quantity is greater than 30')
(10341, 8, 'The quantity is under 30')
(10341, 9, 'The quantity is under 30')
(10342, 24, 'The quantity is under 30')
(10342, 56, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10343, 50, 'The quantity is greater than 30')
(10343, 4, 'The quantity is under 30')
(10343, 15, 'The quantity is under 30')
(10344, 35, 'The quantity is greater than 30')
(10344, 70, 'The quantity is greater than 30')
(10345, 70, 'The quantity is greater than 30')
(10345, 80, 'The quantity is greater than 30')
(10345, 9, 'The quantity is under 30')
(10346, 36, 'The quantity is greater than 30')
(10346, 20, 'The quantity is under 30')
(10347, 10, 'The quantity is under 30')
(10347, 50, 'The quantity is greater than 30')
(10347, 4, 'The quantity is under 30')
(10347, 6, 'The quantity is under 30')
(10348, 15, 'The quantity is under 30')
(10348, 25, 'The quantity is under 30')
(10349, 24, 'The quantity is under 30')
(10350, 15, 'The quantity is under 30')
(10350, 18, 'The quantity is under 30')
(10351, 20, 'The quantity is under 30')
(10351, 13, 'The quantity is under 30')
(10351, 77, 'The quantity is greater than 30')
(10351, 10, 'The quantity is under 30')
(10352, 10, 'The quantity is under 30')
(10352, 20, 'The quantity is under 30')
(10353, 12, 'The quantity is under 30')
(10353, 50, 'The quantity is greater than 30')
(10354, 12, 'The quantity is under 30')
(10354, 4, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10356, 30, 'The quantity is 30')
(10356, 12, 'The quantity is under 30')
(10356, 20, 'The quantity is under 30')
(10357, 30, 'The quantity is 30')
(10357, 16, 'The quantity is under 30')
(10357, 8, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 20, 'The quantity is under 30')
(10359, 56, 'The quantity is greater than 30')
(10359, 70, 'The quantity is greater than 30')
(10359, 80, 'The quantity is greater than 30')
(10360, 30, 'The quantity is 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 10, 'The quantity is under 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 28, 'The quantity is under 30')
(10361, 54, 'The quantity is greater than 30')
(10361, 55, 'The quantity is greater than 30')
(10362, 50, 'The quantity is greater than 30')
(10362, 20, 'The quantity is under 30')
(10362, 24, 'The quantity is under 30')
(10363, 20, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10364, 30, 'The quantity is 30')
(10364, 5, 'The quantity is under 30')
(10365, 24, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10367, 36, 'The quantity is greater than 30')
(10367, 18, 'The quantity is under 30')
(10367, 15, 'The quantity is under 30')
(10367, 7, 'The quantity is under 30')
(10368, 5, 'The quantity is under 30')
(10368, 13, 'The quantity is under 30')
(10368, 25, 'The quantity is under 30')
(10368, 35, 'The quantity is greater than 30')
(10369, 20, 'The quantity is under 30')
(10369, 18, 'The quantity is under 30')
(10370, 15, 'The quantity is under 30')
(10370, 30, 'The quantity is 30')
(10370, 20, 'The quantity is under 30')
(10371, 6, 'The quantity is under 30')
(10372, 12, 'The quantity is under 30')
(10372, 40, 'The quantity is greater than 30')
(10372, 70, 'The quantity is greater than 30')
(10372, 42, 'The quantity is greater than 30')
(10373, 80, 'The quantity is greater than 30')
(10373, 50, 'The quantity is greater than 30')
(10374, 30, 'The quantity is 30')
(10374, 15, 'The quantity is under 30')
(10375, 15, 'The quantity is under 30')
(10375, 10, 'The quantity is under 30')
(10376, 42, 'The quantity is greater than 30')
(10377, 20, 'The quantity is under 30')
(10377, 20, 'The quantity is under 30')
(10378, 6, 'The quantity is under 30')
(10379, 8, 'The quantity is under 30')
(10379, 16, 'The quantity is under 30')
(10379, 20, 'The quantity is under 30')
(10380, 18, 'The quantity is under 30')
(10380, 20, 'The quantity is under 30')
(10380, 6, 'The quantity is under 30')
(10380, 30, 'The quantity is 30')
(10381, 14, 'The quantity is under 30')
(10382, 32, 'The quantity is greater than 30')
(10382, 9, 'The quantity is under 30')
(10382, 14, 'The quantity is under 30')
(10382, 60, 'The quantity is greater than 30')
(10382, 50, 'The quantity is greater than 30')
(10383, 20, 'The quantity is under 30')
(10383, 15, 'The quantity is under 30')
(10383, 20, 'The quantity is under 30')
(10384, 28, 'The quantity is under 30')
(10384, 15, 'The quantity is under 30')
(10385, 10, 'The quantity is under 30')
(10385, 20, 'The quantity is under 30')
(10385, 8, 'The quantity is under 30')
(10386, 15, 'The quantity is under 30')
(10386, 10, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10387, 6, 'The quantity is under 30')
(10387, 12, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10388, 15, 'The quantity is under 30')
(10388, 20, 'The quantity is under 30')
(10388, 40, 'The quantity is greater than 30')
(10389, 16, 'The quantity is under 30')
(10389, 15, 'The quantity is under 30')
(10389, 20, 'The quantity is under 30')
(10389, 30, 'The quantity is 30')
(10390, 60, 'The quantity is greater than 30')
(10390, 40, 'The quantity is greater than 30')
(10390, 45, 'The quantity is greater than 30')
(10390, 24, 'The quantity is under 30')
(10391, 18, 'The quantity is under 30')
(10392, 50, 'The quantity is greater than 30')
(10393, 25, 'The quantity is under 30')
(10393, 42, 'The quantity is greater than 30')
(10393, 7, 'The quantity is under 30')
(10393, 70, 'The quantity is greater than 30')
(10393, 32, 'The quantity is greater than 30')
(10394, 10, 'The quantity is under 30')
(10394, 10, 'The quantity is under 30')
(10395, 28, 'The quantity is under 30')
(10395, 70, 'The quantity is greater than 30')
(10395, 8, 'The quantity is under 30')
(10396, 40, 'The quantity is greater than 30')
(10396, 60, 'The quantity is greater than 30')
(10396, 21, 'The quantity is under 30')
(10397, 10, 'The quantity is under 30')
(10397, 18, 'The quantity is under 30')
(10398, 30, 'The quantity is 30')
(10398, 120, 'The quantity is greater than 30')
(10399, 60, 'The quantity is greater than 30')
(10399, 30, 'The quantity is 30')
(10399, 35, 'The quantity is greater than 30')
(10399, 14, 'The quantity is under 30')
(10400, 21, 'The quantity is under 30')
(10400, 35, 'The quantity is greater than 30')
(10400, 30, 'The quantity is 30')
(10401, 18, 'The quantity is under 30')
(10401, 70, 'The quantity is greater than 30')
(10401, 20, 'The quantity is under 30')
(10401, 60, 'The quantity is greater than 30')
(10402, 60, 'The quantity is greater than 30')
(10402, 65, 'The quantity is greater than 30')
(10403, 21, 'The quantity is under 30')
(10403, 70, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10404, 40, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10405, 50, 'The quantity is greater than 30')
(10406, 10, 'The quantity is under 30')
(10406, 30, 'The quantity is 30')
(10406, 42, 'The quantity is greater than 30')
(10406, 5, 'The quantity is under 30')
(10406, 2, 'The quantity is under 30')
(10407, 30, 'The quantity is 30')
(10407, 15, 'The quantity is under 30')
(10407, 15, 'The quantity is under 30')
(10408, 10, 'The quantity is under 30')
(10408, 6, 'The quantity is under 30')
(10408, 35, 'The quantity is greater than 30')
(10409, 12, 'The quantity is under 30')
(10409, 12, 'The quantity is under 30')
(10410, 49, 'The quantity is greater than 30')
(10410, 16, 'The quantity is under 30')
(10411, 25, 'The quantity is under 30')
(10411, 40, 'The quantity is greater than 30')
(10411, 9, 'The quantity is under 30')
(10412, 20, 'The quantity is under 30')
(10413, 24, 'The quantity is under 30')
(10413, 40, 'The quantity is greater than 30')
(10413, 14, 'The quantity is under 30')
(10414, 18, 'The quantity is under 30')
(10414, 50, 'The quantity is greater than 30')
(10415, 2, 'The quantity is under 30')
(10415, 20, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10416, 10, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10417, 50, 'The quantity is greater than 30')
(10417, 2, 'The quantity is under 30')
(10417, 36, 'The quantity is greater than 30')
(10417, 35, 'The quantity is greater than 30')
(10418, 60, 'The quantity is greater than 30')
(10418, 55, 'The quantity is greater than 30')
(10418, 16, 'The quantity is under 30')
(10418, 15, 'The quantity is under 30')
(10419, 60, 'The quantity is greater than 30')
(10419, 20, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10420, 2, 'The quantity is under 30')
(10420, 8, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10421, 4, 'The quantity is under 30')
(10421, 30, 'The quantity is 30')
(10421, 15, 'The quantity is under 30')
(10421, 10, 'The quantity is under 30')
(10422, 2, 'The quantity is under 30')
(10423, 14, 'The quantity is under 30')
(10423, 20, 'The quantity is under 30')
(10424, 60, 'The quantity is greater than 30')
(10424, 49, 'The quantity is greater than 30')
(10424, 30, 'The quantity is 30')
(10425, 10, 'The quantity is under 30')
(10425, 20, 'The quantity is under 30')
(10426, 5, 'The quantity is under 30')
(10426, 7, 'The quantity is under 30')
(10427, 35, 'The quantity is greater than 30')
(10428, 20, 'The quantity is under 30')
(10429, 40, 'The quantity is greater than 30')
(10429, 35, 'The quantity is greater than 30')
(10430, 45, 'The quantity is greater than 30')
(10430, 50, 'The quantity is greater than 30')
(10430, 30, 'The quantity is 30')
(10430, 70, 'The quantity is greater than 30')

In [87]:

cursor = conn.cursor()
query = ''' 
SELECT OrderID, Quantity,
CASE
    WHEN Quantity > 30 THEN 'The quantity is greater than 30'
    WHEN Quantity = 30 THEN 'The quantity is 30'
    ELSE 'The quantity is under 30'
END AS QuantityText
FROM OrderDetails;
'''
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['OrderID', 'Quantity', 'QuantityText']
(10248, 12, 'The quantity is under 30')
(10248, 10, 'The quantity is under 30')
(10248, 5, 'The quantity is under 30')
(10249, 9, 'The quantity is under 30')
(10249, 40, 'The quantity is greater than 30')
(10250, 10, 'The quantity is under 30')
(10250, 35, 'The quantity is greater than 30')
(10250, 15, 'The quantity is under 30')
(10251, 6, 'The quantity is under 30')
(10251, 15, 'The quantity is under 30')
(10251, 20, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10252, 25, 'The quantity is under 30')
(10252, 40, 'The quantity is greater than 30')
(10253, 20, 'The quantity is under 30')
(10253, 42, 'The quantity is greater than 30')
(10253, 40, 'The quantity is greater than 30')
(10254, 15, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10254, 21, 'The quantity is under 30')
(10255, 20, 'The quantity is under 30')
(10255, 35, 'The quantity is greater than 30')
(10255, 25, 'The quantity is under 30')
(10255, 30, 'The quantity is 30')
(10256, 15, 'The quantity is under 30')
(10256, 12, 'The quantity is under 30')
(10257, 25, 'The quantity is under 30')
(10257, 6, 'The quantity is under 30')
(10257, 15, 'The quantity is under 30')
(10258, 50, 'The quantity is greater than 30')
(10258, 65, 'The quantity is greater than 30')
(10258, 6, 'The quantity is under 30')
(10259, 10, 'The quantity is under 30')
(10259, 1, 'The quantity is under 30')
(10260, 16, 'The quantity is under 30')
(10260, 50, 'The quantity is greater than 30')
(10260, 15, 'The quantity is under 30')
(10260, 21, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10261, 20, 'The quantity is under 30')
(10262, 12, 'The quantity is under 30')
(10262, 15, 'The quantity is under 30')
(10262, 2, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 28, 'The quantity is under 30')
(10263, 60, 'The quantity is greater than 30')
(10263, 36, 'The quantity is greater than 30')
(10264, 35, 'The quantity is greater than 30')
(10264, 25, 'The quantity is under 30')
(10265, 30, 'The quantity is 30')
(10265, 20, 'The quantity is under 30')
(10266, 12, 'The quantity is under 30')
(10267, 50, 'The quantity is greater than 30')
(10267, 70, 'The quantity is greater than 30')
(10267, 15, 'The quantity is under 30')
(10268, 10, 'The quantity is under 30')
(10268, 4, 'The quantity is under 30')
(10269, 60, 'The quantity is greater than 30')
(10269, 20, 'The quantity is under 30')
(10270, 30, 'The quantity is 30')
(10270, 25, 'The quantity is under 30')
(10271, 24, 'The quantity is under 30')
(10272, 6, 'The quantity is under 30')
(10272, 40, 'The quantity is greater than 30')
(10272, 24, 'The quantity is under 30')
(10273, 24, 'The quantity is under 30')
(10273, 15, 'The quantity is under 30')
(10273, 20, 'The quantity is under 30')
(10273, 60, 'The quantity is greater than 30')
(10273, 33, 'The quantity is greater than 30')
(10274, 20, 'The quantity is under 30')
(10274, 7, 'The quantity is under 30')
(10275, 12, 'The quantity is under 30')
(10275, 6, 'The quantity is under 30')
(10276, 15, 'The quantity is under 30')
(10276, 10, 'The quantity is under 30')
(10277, 20, 'The quantity is under 30')
(10277, 12, 'The quantity is under 30')
(10278, 16, 'The quantity is under 30')
(10278, 15, 'The quantity is under 30')
(10278, 8, 'The quantity is under 30')
(10278, 25, 'The quantity is under 30')
(10279, 15, 'The quantity is under 30')
(10280, 12, 'The quantity is under 30')
(10280, 20, 'The quantity is under 30')
(10280, 30, 'The quantity is 30')
(10281, 1, 'The quantity is under 30')
(10281, 6, 'The quantity is under 30')
(10281, 4, 'The quantity is under 30')
(10282, 6, 'The quantity is under 30')
(10282, 2, 'The quantity is under 30')
(10283, 20, 'The quantity is under 30')
(10283, 18, 'The quantity is under 30')
(10283, 35, 'The quantity is greater than 30')
(10283, 3, 'The quantity is under 30')
(10284, 15, 'The quantity is under 30')
(10284, 21, 'The quantity is under 30')
(10284, 20, 'The quantity is under 30')
(10284, 5, 'The quantity is under 30')
(10285, 45, 'The quantity is greater than 30')
(10285, 40, 'The quantity is greater than 30')
(10285, 36, 'The quantity is greater than 30')
(10286, 100, 'The quantity is greater than 30')
(10286, 40, 'The quantity is greater than 30')
(10287, 40, 'The quantity is greater than 30')
(10287, 20, 'The quantity is under 30')
(10287, 15, 'The quantity is under 30')
(10288, 10, 'The quantity is under 30')
(10288, 3, 'The quantity is under 30')
(10289, 30, 'The quantity is 30')
(10289, 9, 'The quantity is under 30')
(10290, 20, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 15, 'The quantity is under 30')
(10290, 10, 'The quantity is under 30')
(10291, 20, 'The quantity is under 30')
(10291, 24, 'The quantity is under 30')
(10291, 2, 'The quantity is under 30')
(10292, 20, 'The quantity is under 30')
(10293, 12, 'The quantity is under 30')
(10293, 10, 'The quantity is under 30')
(10293, 5, 'The quantity is under 30')
(10293, 6, 'The quantity is under 30')
(10294, 18, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 15, 'The quantity is under 30')
(10294, 21, 'The quantity is under 30')
(10294, 6, 'The quantity is under 30')
(10295, 4, 'The quantity is under 30')
(10296, 12, 'The quantity is under 30')
(10296, 30, 'The quantity is 30')
(10296, 15, 'The quantity is under 30')
(10297, 60, 'The quantity is greater than 30')
(10297, 20, 'The quantity is under 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 40, 'The quantity is greater than 30')
(10298, 30, 'The quantity is 30')
(10298, 15, 'The quantity is under 30')
(10299, 15, 'The quantity is under 30')
(10299, 20, 'The quantity is under 30')
(10300, 30, 'The quantity is 30')
(10300, 20, 'The quantity is under 30')
(10301, 10, 'The quantity is under 30')
(10301, 20, 'The quantity is under 30')
(10302, 40, 'The quantity is greater than 30')
(10302, 28, 'The quantity is under 30')
(10302, 12, 'The quantity is under 30')
(10303, 40, 'The quantity is greater than 30')
(10303, 30, 'The quantity is 30')
(10303, 15, 'The quantity is under 30')
(10304, 30, 'The quantity is 30')
(10304, 10, 'The quantity is under 30')
(10304, 2, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 25, 'The quantity is under 30')
(10305, 30, 'The quantity is 30')
(10306, 10, 'The quantity is under 30')
(10306, 10, 'The quantity is under 30')
(10306, 5, 'The quantity is under 30')
(10307, 10, 'The quantity is under 30')
(10307, 3, 'The quantity is under 30')
(10308, 1, 'The quantity is under 30')
(10308, 5, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 30, 'The quantity is 30')
(10309, 2, 'The quantity is under 30')
(10309, 20, 'The quantity is under 30')
(10309, 3, 'The quantity is under 30')
(10310, 10, 'The quantity is under 30')
(10310, 5, 'The quantity is under 30')
(10311, 6, 'The quantity is under 30')
(10311, 7, 'The quantity is under 30')
(10312, 4, 'The quantity is under 30')
(10312, 24, 'The quantity is under 30')
(10312, 20, 'The quantity is under 30')
(10312, 10, 'The quantity is under 30')
(10313, 12, 'The quantity is under 30')
(10314, 40, 'The quantity is greater than 30')
(10314, 30, 'The quantity is 30')
(10314, 25, 'The quantity is under 30')
(10315, 14, 'The quantity is under 30')
(10315, 30, 'The quantity is 30')
(10316, 10, 'The quantity is under 30')
(10316, 70, 'The quantity is greater than 30')
(10317, 20, 'The quantity is under 30')
(10318, 20, 'The quantity is under 30')
(10318, 6, 'The quantity is under 30')
(10319, 8, 'The quantity is under 30')
(10319, 14, 'The quantity is under 30')
(10319, 30, 'The quantity is 30')
(10320, 30, 'The quantity is 30')
(10321, 10, 'The quantity is under 30')
(10322, 20, 'The quantity is under 30')
(10323, 5, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10323, 4, 'The quantity is under 30')
(10324, 21, 'The quantity is under 30')
(10324, 70, 'The quantity is greater than 30')
(10324, 30, 'The quantity is 30')
(10324, 40, 'The quantity is greater than 30')
(10324, 80, 'The quantity is greater than 30')
(10325, 6, 'The quantity is under 30')
(10325, 12, 'The quantity is under 30')
(10325, 9, 'The quantity is under 30')
(10325, 4, 'The quantity is under 30')
(10325, 40, 'The quantity is greater than 30')
(10326, 24, 'The quantity is under 30')
(10326, 16, 'The quantity is under 30')
(10326, 50, 'The quantity is greater than 30')
(10327, 25, 'The quantity is under 30')
(10327, 50, 'The quantity is greater than 30')
(10327, 35, 'The quantity is greater than 30')
(10327, 30, 'The quantity is 30')
(10328, 9, 'The quantity is under 30')
(10328, 40, 'The quantity is greater than 30')
(10328, 10, 'The quantity is under 30')
(10329, 10, 'The quantity is under 30')
(10329, 8, 'The quantity is under 30')
(10329, 20, 'The quantity is under 30')
(10329, 12, 'The quantity is under 30')
(10330, 50, 'The quantity is greater than 30')
(10330, 25, 'The quantity is under 30')
(10331, 15, 'The quantity is under 30')
(10332, 40, 'The quantity is greater than 30')
(10332, 10, 'The quantity is under 30')
(10332, 16, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 10, 'The quantity is under 30')
(10333, 40, 'The quantity is greater than 30')
(10334, 8, 'The quantity is under 30')
(10334, 10, 'The quantity is under 30')
(10335, 7, 'The quantity is under 30')
(10335, 25, 'The quantity is under 30')
(10335, 6, 'The quantity is under 30')
(10335, 48, 'The quantity is greater than 30')
(10336, 18, 'The quantity is under 30')
(10337, 40, 'The quantity is greater than 30')
(10337, 24, 'The quantity is under 30')
(10337, 20, 'The quantity is under 30')
(10337, 28, 'The quantity is under 30')
(10337, 25, 'The quantity is under 30')
(10338, 20, 'The quantity is under 30')
(10338, 15, 'The quantity is under 30')
(10339, 10, 'The quantity is under 30')
(10339, 70, 'The quantity is greater than 30')
(10339, 28, 'The quantity is under 30')
(10340, 20, 'The quantity is under 30')
(10340, 12, 'The quantity is under 30')
(10340, 40, 'The quantity is greater than 30')
(10341, 8, 'The quantity is under 30')
(10341, 9, 'The quantity is under 30')
(10342, 24, 'The quantity is under 30')
(10342, 56, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10342, 40, 'The quantity is greater than 30')
(10343, 50, 'The quantity is greater than 30')
(10343, 4, 'The quantity is under 30')
(10343, 15, 'The quantity is under 30')
(10344, 35, 'The quantity is greater than 30')
(10344, 70, 'The quantity is greater than 30')
(10345, 70, 'The quantity is greater than 30')
(10345, 80, 'The quantity is greater than 30')
(10345, 9, 'The quantity is under 30')
(10346, 36, 'The quantity is greater than 30')
(10346, 20, 'The quantity is under 30')
(10347, 10, 'The quantity is under 30')
(10347, 50, 'The quantity is greater than 30')
(10347, 4, 'The quantity is under 30')
(10347, 6, 'The quantity is under 30')
(10348, 15, 'The quantity is under 30')
(10348, 25, 'The quantity is under 30')
(10349, 24, 'The quantity is under 30')
(10350, 15, 'The quantity is under 30')
(10350, 18, 'The quantity is under 30')
(10351, 20, 'The quantity is under 30')
(10351, 13, 'The quantity is under 30')
(10351, 77, 'The quantity is greater than 30')
(10351, 10, 'The quantity is under 30')
(10352, 10, 'The quantity is under 30')
(10352, 20, 'The quantity is under 30')
(10353, 12, 'The quantity is under 30')
(10353, 50, 'The quantity is greater than 30')
(10354, 12, 'The quantity is under 30')
(10354, 4, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10355, 25, 'The quantity is under 30')
(10356, 30, 'The quantity is 30')
(10356, 12, 'The quantity is under 30')
(10356, 20, 'The quantity is under 30')
(10357, 30, 'The quantity is 30')
(10357, 16, 'The quantity is under 30')
(10357, 8, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 10, 'The quantity is under 30')
(10358, 20, 'The quantity is under 30')
(10359, 56, 'The quantity is greater than 30')
(10359, 70, 'The quantity is greater than 30')
(10359, 80, 'The quantity is greater than 30')
(10360, 30, 'The quantity is 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 10, 'The quantity is under 30')
(10360, 35, 'The quantity is greater than 30')
(10360, 28, 'The quantity is under 30')
(10361, 54, 'The quantity is greater than 30')
(10361, 55, 'The quantity is greater than 30')
(10362, 50, 'The quantity is greater than 30')
(10362, 20, 'The quantity is under 30')
(10362, 24, 'The quantity is under 30')
(10363, 20, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10363, 12, 'The quantity is under 30')
(10364, 30, 'The quantity is 30')
(10364, 5, 'The quantity is under 30')
(10365, 24, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10366, 5, 'The quantity is under 30')
(10367, 36, 'The quantity is greater than 30')
(10367, 18, 'The quantity is under 30')
(10367, 15, 'The quantity is under 30')
(10367, 7, 'The quantity is under 30')
(10368, 5, 'The quantity is under 30')
(10368, 13, 'The quantity is under 30')
(10368, 25, 'The quantity is under 30')
(10368, 35, 'The quantity is greater than 30')
(10369, 20, 'The quantity is under 30')
(10369, 18, 'The quantity is under 30')
(10370, 15, 'The quantity is under 30')
(10370, 30, 'The quantity is 30')
(10370, 20, 'The quantity is under 30')
(10371, 6, 'The quantity is under 30')
(10372, 12, 'The quantity is under 30')
(10372, 40, 'The quantity is greater than 30')
(10372, 70, 'The quantity is greater than 30')
(10372, 42, 'The quantity is greater than 30')
(10373, 80, 'The quantity is greater than 30')
(10373, 50, 'The quantity is greater than 30')
(10374, 30, 'The quantity is 30')
(10374, 15, 'The quantity is under 30')
(10375, 15, 'The quantity is under 30')
(10375, 10, 'The quantity is under 30')
(10376, 42, 'The quantity is greater than 30')
(10377, 20, 'The quantity is under 30')
(10377, 20, 'The quantity is under 30')
(10378, 6, 'The quantity is under 30')
(10379, 8, 'The quantity is under 30')
(10379, 16, 'The quantity is under 30')
(10379, 20, 'The quantity is under 30')
(10380, 18, 'The quantity is under 30')
(10380, 20, 'The quantity is under 30')
(10380, 6, 'The quantity is under 30')
(10380, 30, 'The quantity is 30')
(10381, 14, 'The quantity is under 30')
(10382, 32, 'The quantity is greater than 30')
(10382, 9, 'The quantity is under 30')
(10382, 14, 'The quantity is under 30')
(10382, 60, 'The quantity is greater than 30')
(10382, 50, 'The quantity is greater than 30')
(10383, 20, 'The quantity is under 30')
(10383, 15, 'The quantity is under 30')
(10383, 20, 'The quantity is under 30')
(10384, 28, 'The quantity is under 30')
(10384, 15, 'The quantity is under 30')
(10385, 10, 'The quantity is under 30')
(10385, 20, 'The quantity is under 30')
(10385, 8, 'The quantity is under 30')
(10386, 15, 'The quantity is under 30')
(10386, 10, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10387, 6, 'The quantity is under 30')
(10387, 12, 'The quantity is under 30')
(10387, 15, 'The quantity is under 30')
(10388, 15, 'The quantity is under 30')
(10388, 20, 'The quantity is under 30')
(10388, 40, 'The quantity is greater than 30')
(10389, 16, 'The quantity is under 30')
(10389, 15, 'The quantity is under 30')
(10389, 20, 'The quantity is under 30')
(10389, 30, 'The quantity is 30')
(10390, 60, 'The quantity is greater than 30')
(10390, 40, 'The quantity is greater than 30')
(10390, 45, 'The quantity is greater than 30')
(10390, 24, 'The quantity is under 30')
(10391, 18, 'The quantity is under 30')
(10392, 50, 'The quantity is greater than 30')
(10393, 25, 'The quantity is under 30')
(10393, 42, 'The quantity is greater than 30')
(10393, 7, 'The quantity is under 30')
(10393, 70, 'The quantity is greater than 30')
(10393, 32, 'The quantity is greater than 30')
(10394, 10, 'The quantity is under 30')
(10394, 10, 'The quantity is under 30')
(10395, 28, 'The quantity is under 30')
(10395, 70, 'The quantity is greater than 30')
(10395, 8, 'The quantity is under 30')
(10396, 40, 'The quantity is greater than 30')
(10396, 60, 'The quantity is greater than 30')
(10396, 21, 'The quantity is under 30')
(10397, 10, 'The quantity is under 30')
(10397, 18, 'The quantity is under 30')
(10398, 30, 'The quantity is 30')
(10398, 120, 'The quantity is greater than 30')
(10399, 60, 'The quantity is greater than 30')
(10399, 30, 'The quantity is 30')
(10399, 35, 'The quantity is greater than 30')
(10399, 14, 'The quantity is under 30')
(10400, 21, 'The quantity is under 30')
(10400, 35, 'The quantity is greater than 30')
(10400, 30, 'The quantity is 30')
(10401, 18, 'The quantity is under 30')
(10401, 70, 'The quantity is greater than 30')
(10401, 20, 'The quantity is under 30')
(10401, 60, 'The quantity is greater than 30')
(10402, 60, 'The quantity is greater than 30')
(10402, 65, 'The quantity is greater than 30')
(10403, 21, 'The quantity is under 30')
(10403, 70, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10404, 40, 'The quantity is greater than 30')
(10404, 30, 'The quantity is 30')
(10405, 50, 'The quantity is greater than 30')
(10406, 10, 'The quantity is under 30')
(10406, 30, 'The quantity is 30')
(10406, 42, 'The quantity is greater than 30')
(10406, 5, 'The quantity is under 30')
(10406, 2, 'The quantity is under 30')
(10407, 30, 'The quantity is 30')
(10407, 15, 'The quantity is under 30')
(10407, 15, 'The quantity is under 30')
(10408, 10, 'The quantity is under 30')
(10408, 6, 'The quantity is under 30')
(10408, 35, 'The quantity is greater than 30')
(10409, 12, 'The quantity is under 30')
(10409, 12, 'The quantity is under 30')
(10410, 49, 'The quantity is greater than 30')
(10410, 16, 'The quantity is under 30')
(10411, 25, 'The quantity is under 30')
(10411, 40, 'The quantity is greater than 30')
(10411, 9, 'The quantity is under 30')
(10412, 20, 'The quantity is under 30')
(10413, 24, 'The quantity is under 30')
(10413, 40, 'The quantity is greater than 30')
(10413, 14, 'The quantity is under 30')
(10414, 18, 'The quantity is under 30')
(10414, 50, 'The quantity is greater than 30')
(10415, 2, 'The quantity is under 30')
(10415, 20, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10416, 10, 'The quantity is under 30')
(10416, 20, 'The quantity is under 30')
(10417, 50, 'The quantity is greater than 30')
(10417, 2, 'The quantity is under 30')
(10417, 36, 'The quantity is greater than 30')
(10417, 35, 'The quantity is greater than 30')
(10418, 60, 'The quantity is greater than 30')
(10418, 55, 'The quantity is greater than 30')
(10418, 16, 'The quantity is under 30')
(10418, 15, 'The quantity is under 30')
(10419, 60, 'The quantity is greater than 30')
(10419, 20, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10420, 2, 'The quantity is under 30')
(10420, 8, 'The quantity is under 30')
(10420, 20, 'The quantity is under 30')
(10421, 4, 'The quantity is under 30')
(10421, 30, 'The quantity is 30')
(10421, 15, 'The quantity is under 30')
(10421, 10, 'The quantity is under 30')
(10422, 2, 'The quantity is under 30')
(10423, 14, 'The quantity is under 30')
(10423, 20, 'The quantity is under 30')
(10424, 60, 'The quantity is greater than 30')
(10424, 49, 'The quantity is greater than 30')
(10424, 30, 'The quantity is 30')
(10425, 10, 'The quantity is under 30')
(10425, 20, 'The quantity is under 30')
(10426, 5, 'The quantity is under 30')
(10426, 7, 'The quantity is under 30')
(10427, 35, 'The quantity is greater than 30')
(10428, 20, 'The quantity is under 30')
(10429, 40, 'The quantity is greater than 30')
(10429, 35, 'The quantity is greater than 30')
(10430, 45, 'The quantity is greater than 30')
(10430, 50, 'The quantity is greater than 30')
(10430, 30, 'The quantity is 30')
(10430, 70, 'The quantity is greater than 30')

### -- 주석

In [88]:

cursor = conn.cursor()
query = ''' 
SELECT * FROM Customers -- WHERE City='Berlin';
'''
cursor.execute(query)
column_names = [description[0] for description in cursor.description]
print(column_names)
for row in cursor:
    print(row)

['CustomerID', 'CustomerName', 'ContactName', 'Address', 'City', 'PostalCode', 'Country']
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany')
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico')
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico')
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK')
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden')
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany')
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France')
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain')
(9, "Bon app'", 'Laurence Lebihans', '12, rue des Bouchers', 'Marseille', '13008', 'France')
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada')
(11, "B's Beverages", 'Victoria Ashworth', 'Fauntleroy Circus', 'London', 'EC2 5NT', 'UK')
(12, 'Cactus Comidas para llevar', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina')
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico')
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland')
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil')
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery ', 'London', 'WX1 6LT', 'UK')
(17, 'Drachenblut Delikatessend', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany')
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France')
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK')
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria')
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil')
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain')
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France')
(24, 'Folk och fä HB', 'Maria Larsson', 'Åkergatan 24', 'Bräcke', 'S-844 67', 'Sweden')
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany')
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France')
(27, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy')
(28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez ', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal')
(29, 'Galería del gastrónomo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '08022', 'Spain')
(30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain')
(31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil')
(32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA')
(33, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas', '1081', 'Venezuela')
(34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil')
(35, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela')
(36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA')
(37, 'Hungry Owl All-Night Grocers', 'Patricia McKenna', '8 Johnstown Road', 'Cork', None, 'Ireland')
(38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK')
(39, 'Königlich Essen', 'Philip Cramer', 'Maubelstr. 90', 'Brandenburg', '14776', 'Germany')
(40, "La corne d'abondance", 'Daniel Tonini', "67, avenue de l'Europe", 'Versailles', '78000', 'France')
(41, "La maison d'Asie", 'Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse', '31000', 'France')
(42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada')
(43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA')
(44, 'Lehmanns Marktstand', 'Renate Messner', 'Magazinweg 7', 'Frankfurt a.M. ', '60528', 'Germany')
(45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA')
(46, 'LILA-Supermercado', 'Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', '3508', 'Venezuela')
(47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela')
(48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA')
(49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy')
(50, 'Maison Dewey', 'Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles', 'B-1180', 'Belgium')
(51, 'Mère Paillarde', 'Jean Fresnière', '43 rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada')
(52, 'Morgenstern Gesundkost', 'Alexander Feuer', 'Heerstr. 22', 'Leipzig', '04179', 'Germany')
(53, 'North/South', 'Simon Crowther', 'South House 300 Queensbridge', 'London', 'SW7 1RZ', 'UK')
(54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina')
(55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA')
(56, 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Mehrheimerstr. 369', 'Köln', '50739', 'Germany')
(57, 'Paris spécialités', 'Marie Bertrand', '265, boulevard Charonne', 'Paris', '75012', 'France')
(58, 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Calle Dr. Jorge Cash 321', 'México D.F.', '05033', 'Mexico')
(59, 'Piccolo und mehr', 'Georg Pipps', 'Geislweg 14', 'Salzburg', '5020', 'Austria')
(60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal')
(61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil')
(62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil')
(63, 'QUICK-Stop', 'Horst Kloss', 'Taucherstraße 10', 'Cunewalde', '01307', 'Germany')
(64, 'Rancho grande', 'Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires', '1010', 'Argentina')
(65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA')
(66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy')
(67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil')
(68, 'Richter Supermarkt', 'Michael Holz', 'Grenzacherweg 237', 'Genève', '1203', 'Switzerland')
(69, 'Romero y tomillo', 'Alejandra Camino', 'Gran Vía, 1', 'Madrid', '28001', 'Spain')
(70, 'Santé Gourmet', 'Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern', '4110', 'Norway')
(71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA')
(72, 'Seven Seas Imports', 'Hari Kumar', '90 Wadhurst Rd.', 'London', 'OX15 4NB', 'UK')
(73, 'Simons bistro', 'Jytte Petersen', 'Vinbæltet 34', 'København', '1734', 'Denmark')
(74, 'Spécialités du monde', 'Dominique Perrier', '25, rue Lauriston', 'Paris', '75016', 'France')
(75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA')
(76, 'Suprêmes délices', 'Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi', 'B-6000', 'Belgium')
(77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA')
(78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA')
(79, 'Toms Spezialitäten', 'Karin Josephs', 'Luisenstr. 48', 'Münster', '44087', 'Germany')
(80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '05033', 'Mexico')
(81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil')
(82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')
(83, 'Vaffeljernet', 'Palle Ibsen', 'Smagsløget 45', 'Århus', '8200', 'Denmark')
(84, 'Victuailles en stock', 'Mary Saveley', '2, rue du Commerce', 'Lyon', '69004', 'France')
(85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France')
(86, 'Die Wandernde Kuh', 'Rita Müller', 'Adenauerallee 900', 'Stuttgart', '70563', 'Germany')
(87, 'Wartian Herkku', 'Pirkko Koskitalo', 'Torikatu 38', 'Oulu', '90110', 'Finland')
(88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')
(89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')
(90, 'Wilman Kala', 'Matti Karttunen', 'Keskuskatu 45', 'Helsinki', '21240', 'Finland')
(91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', None)
(None, 'Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway')
(None, 'Greasy Burger', 'Per Olsen', 'Gateveien 15', 'Sandnes', '4306', 'Norway')
(None, 'Tasty Tee', 'Finn Egan', 'Streetroad 19B', 'Liverpool', 'L1 0AA', 'UK')
(None, 'Exotic Liquid', None, None, 'Londona', None, 'UK')
(None, 'New Orleans Cajun Delights', None, None, 'New Orleans', None, 'USA')
(None, "Grandma Kelly's Homestead", None, None, 'Ann Arbor', None, 'USA')
(None, 'Tokyo Traders', None, None, 'Tokyo', None, 'Japan')
(None, "Cooperativa de Quesos 'Las Cabras'", None, None, 'Oviedo', None, 'Spain')
(None, "Mayumi's", None, None, 'Osaka', None, 'Japan')
(None, 'Pavlova, Ltd.', None, None, 'Melbourne', None, 'Australia')
(None, 'Specialty Biscuits, Ltd.', None, None, 'Manchester', None, 'UK')
(None, 'PB Knäckebröd AB', None, None, 'Göteborg', None, 'Sweden ')
(None, 'Refrescos Americanas LTDA', None, None, 'São Paulo', None, 'Brazil')
(None, 'Heli Süßwaren GmbH & Co. KG', None, None, 'Berlin', None, 'Germany')
(None, 'Plutzer Lebensmittelgroßmärkte AG', None, None, 'Frankfurt', None, 'Germany')
(None, 'Nord-Ost-Fisch Handelsgesellschaft mbH', None, None, 'Cuxhaven', None, 'Germany')
(None, 'Formaggi Fortini s.r.l.', None, None, 'Ravenna', None, 'Italy')
(None, 'Norske Meierier', None, None, 'Sandvika', None, 'Norway')
(None, 'Bigfoot Breweries', None, None, 'Bend', None, 'USA')
(None, 'Svensk Sjöföda AB', None, None, 'Stockholm', None, 'Sweden')
(None, 'Aux joyeux ecclésiastiques', None, None, 'Paris', None, 'France')
(None, 'New England Seafood Cannery', None, None, 'Boston', None, 'USA')
(None, 'Leka Trading', None, None, 'Singapore', None, 'Singapore')
(None, 'Lyngbysild', None, None, 'Lyngby', None, 'Denmark')
(None, 'Zaanse Snoepfabriek', None, None, 'Zaandam', None, 'Netherlands')
(None, 'Karkki Oy', None, None, 'Lappeenranta', None, 'Finland')
(None, "G'day, Mate", None, None, 'Sydney', None, 'Australia')
(None, 'Ma Maison', None, None, 'Montréal', None, 'Canada')
(None, 'Pasta Buttini s.r.l.', None, None, 'Salerno', None, 'Italy')
(None, 'Escargots Nouveaux', None, None, 'Montceau', None, 'France')
(None, 'Gai pâturage', None, None, 'Annecy', None, 'France')
(None, "Forêts d'érables", None, None, 'Ste-Hyacinthe', None, 'Canada')

In [ ]:
print(1)